import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const STORAGE_KEY = "app_lang";

const DICTIONARY = {
  en: {
    results: "Results",
    today: "Today",
    calendar: "Schedule",
    table: "Table",
    insights: "Insights",
    picks: "Picks",
    subscriptions: "Subscriptions",
    season: "Season",
    leagues: "Leagues",
    topTournaments: "Top Tournaments",
    quickLeagueNav: "Quick league switch",
    catalog: "Catalog",
    currentLeague: "Current league",
    changeLeague: "Change league",
    chooseLeague: "Choose league",
    searchLeague: "Search league",
    nothingFound: "Nothing found",
    teams: "teams",
    language: "Language",
    countryEngland: "England",
    countrySpain: "Spain",
    countryGermany: "Germany",
    countryItaly: "Italy",
    countryFrance: "France",
    countryEurope: "Europe",
    countryNationalTeams: "National teams",
    countryPortugal: "Portugal",
    countryNetherlands: "Netherlands",
    countryTurkey: "Turkey",
    tournamentMatches: "Tournament matches",
    resultsTitle: "Results",
    resultsLead:
      "Played matches. Tap a match to open Match Center.",
    seasonUpper: "Season",
    loadingMatches: "Loading matches...",
    errorPrefix: "Error",
    noMatches: "No matches for selected filters.",
    openMatchHint: "Tap a match to open Match Center.",
    loadingMoreRounds: "Loading next rounds...",
    matchesCount: "matches",
    calendarEyebrow: "Tournament schedule",
    scheduleTitle: "Match schedule",
    scheduleLead:
      "Upcoming tournament matches. Tap a match to open Match Center.",
    loadingSchedule: "Loading schedule...",
    scheduleErrorPrefix: "Loading error",
    noScheduledMatches: "No scheduled matches for selected season.",
    loadingMatchAnalytics: "Loading match analytics...",
    lockedAnalyticsTitle: "EdgeScore analytics unavailable",
    lockedAnalyticsBody:
      "Unlock predictions, probabilities and market value signals.",
    goToPlans: "Go to plans",
    close: "Close",
    bestPicksTitle: "Betting picks",
    allLeagues: "All leagues",
    bestPicksLead:
      "Two recommendations per match: outcome and total 2.5 with model explanations.",
    round: "Round",
    nearest: "Nearest",
    noRounds: "no rounds",
    loadingPremiumPicks: "Loading premium picks...",
    lineupsLoading: "Loading lineups...",
    startingLineups: "Starting lineups",
    bench: "Bench",
    matchEvents: "Match events",
    homeSide: "Home",
    awaySide: "Away",
    assist: "assist",
    standingsEyebrow: "Tournament table",
    playerStatsEyebrow: "Player stats",
    scorers: "Top scorers",
    assists: "Assists",
    overall: "Overall",
    homeView: "Home",
    awayView: "Away",
    groups: "Groups",
    playoff: "Play-off",
    team: "Team",
    playedShort: "P",
    winsShort: "W",
    drawsShort: "D",
    lossesShort: "L",
    goalsShort: "G",
    pointsShort: "PTS",
    noData: "No data",
    points: "points",
    tableSubtitle:
      "Team positions, points and form for the selected season. Tap a team to open detailed analytics.",
    tableHint:
      "Form shows the last 5 matches. Tap a team to open detailed analytics.",
    scorersSubtitle:
      "Top scorers for the selected league and season. Tap a player to open detailed stats.",
    assistsSubtitle:
      "Top assist providers for the selected league and season. Tap a player to open detailed stats.",
    groupedTableSubtitle:
      "The group stage is split into compact group tables.",
    playoffSubtitle:
      "Play-off bracket by tournament stages, aggregate score and stage outcome.",
    dataLoading: "Loading data...",
    player: "Player",
    goals: "Goals",
    penalties: "Penalties",
    stage: "Stage",
    todayEyebrow: "Matchday overview",
    todayTitle: "What matters today",
    todayLead:
      "Live matches, upcoming fixtures and the quickest paths into EdgeScore.",
    matchOfTheDay: "Match of the day",
    bestSignalToday: "Best signal today",
    livePriority: "Live priority",
    upcomingPriority: "Upcoming focus",
    openMatchCenter: "Open Match Center",
    liveNow: "Live now",
    upcomingSoon: "Upcoming soon",
    topLeaguesShort: "Top leagues",
    openResults: "Open results",
    openSchedule: "Open schedule",
    openPicks: "Open picks",
    openTable: "Open table",
    jumpIn: "Jump in",
    noLiveMatches: "No live matches right now.",
    noUpcomingMatches: "No upcoming matches in this window.",
    viewAll: "View all",
    matchCenter: "Match Center",
    quickActions: "Quick actions",
    productShortAbout:
      "Fast football analytics focused on the matches worth opening now.",
    recentLeagues: "Recent leagues",
    favoriteTeams: "Favorite teams",
    favoriteLeagues: "Favorite leagues",
    favoriteMatches: "Favorite matches",
    noFavoriteTeams: "No favorite teams yet.",
    noFavoriteLeagues: "No favorite leagues yet.",
    noFavoriteMatches: "No favorite matches yet.",
    recentMatches: "Recently viewed matches",
    noRecentMatches: "No recently viewed matches yet.",
    bestPicksToday: "Best picks today",
    noBestPicksToday: "No picks for this window yet.",
    evShort: "EV",
    oddsShort: "Odds",
    noRecentLeagues: "No recent leagues yet.",
    openLeague: "Open league",
    account: "Account",
    accountOverview: "Overview",
    favoritesTab: "Favorites",
    subscriptionsTab: "Subscriptions",
    backHomeShort: "Back home",
    accountClosed: "Access denied",
    accountClosedBody: "Sign in to open your account.",
    signInAction: "Sign in",
    unnamed: "Untitled",
    openCard: "Open card",
    remove: "Remove",
    removeFromFavoritesConfirm: "Remove from favorites?",
    favoritesSectionEyebrow: "Favorites",
    teamsAndPlayers: "Teams and players",
    favoritesAlwaysReady: "Teams and players you want to keep close at hand.",
    favoriteSchedule: "Favorite schedule",
    favoriteResults: "Favorite results",
    teamsLabel: "Teams",
    matchesLabel: "Matches",
    playersLabel: "Players",
    noFavoriteTeamsBody: "You have not added any teams to favorites yet. Add teams to track their form and results.",
    noFavoriteMatchesBody: "You have not added any matches to favorites yet. Save matches to return to them quickly.",
    noFavoritePlayersBody: "You have not added any players to favorites yet. Add players to track their form and results.",
    favoritesTotal: "Favorites",
    goToFavorites: "Open favorites",
    activity: "Activity",
    registrationDateLead: "EdgeScore registration date.",
    edgeScoreInsights: "EdgeScore insights",
    edgeScoreInsightsLead: "Get model explanations and factor breakdowns.",
    openInsights: "Open insights",
    quickLinks: "Quick links",
    matchResults: "Match results",
    scheduleAndPredictions: "Schedule and predictions",
    picksAndBestBets: "Picks and best bets",
    aboutAndContacts: "About and contacts",
    verifiedEmail: "Email verified",
    verifyEmailNeeded: "Email verification required",
    noSubscription: "No subscription",
    teamsCountLabel: "teams",
    matchesCountLabel: "matches",
    playersCountLabel: "players",
    saveMatch: "Save match",
    removeMatch: "Remove match",
    saveLeague: "Save league",
    removeLeague: "Remove league",
    leagueSaved: "League saved",
    matchSaved: "Saved",
    signIn: "Sign In",
    signUp: "Sign Up",
    profile: "Profile",
    logOut: "Log Out",
    loginTitle: "Sign In",
    loginCardTitle: "Sign in to your account",
    registerTitle: "Create account",
    backHome: "Back Home",
    email: "Email",
    emailPlaceholder: "Enter your email",
    passwordPlaceholder: "Enter your password",
    passwordMinPlaceholder: "At least 8 characters",
    password: "Password",
    username: "Username",
    usernamePlaceholder: "Choose a username",
    confirmPassword: "Confirm password",
    confirmPasswordPlaceholder: "Repeat your password",
    loginSubmit: "Sign In",
    loginSubmitting: "Signing in...",
    registerSubmit: "Create Account",
    registerSubmitting: "Creating account...",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    registration: "Registration",
    registrationSuccess: "Registration successful!",
    registrationSuccessBody:
      "Check your email to verify your account. After verification you can sign in.",
    redirectingToLogin: "Redirecting to login in a few seconds...",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 8 characters",
    loginFailed: "Login failed",
    registrationFailed: "Registration failed",
    footballAnalytics: "Football Analytics",
    loginLead: "Use your email and password to access your EdgeScore profile.",
    registerLead: "Create an account to unlock analytics, insights, and premium picks.",
    aboutProject: "About",
    aboutLead:
      "A football analytics platform that helps you understand a match, team form, and market signals faster.",
    whatIsEdgescore: "What is EdgeScore",
    whatIsEdgescoreText:
      "EdgeScore is a football analytics platform. It combines match stats, team form, xG and market odds to present a clearer view of each fixture and highlight interesting scenarios.",
    howItWorks: "How it works",
    howItWorksText:
      "The model evaluates team strength, game tempo, shot quality and pricing inefficiencies. From that it produces outcome and total signals together with a short explanation of why the match looks that way.",
    whatUserGets: "What users get",
    whatUserGetsText:
      "Results, schedules, insights, team and player cards, form comparison, head-to-head context and curated match picks. The product is meant to be a working analysis tool, not a static stats wall.",
    importantToKnow: "Important to know",
    importantToKnowText:
      "EdgeScore provides analytics and model estimates, not guaranteed outcomes. Every signal is probabilistic and the final decision always stays with the user.",
    contacts: "Contact",
    contactLead:
      "For product questions, partnerships, or feedback, use this address.",
    loading: "Loading...",
  },
  ru: {
    results: "Результаты",
    today: "Сегодня",
    calendar: "Календарь",
    table: "Таблица",
    insights: "Инсайты",
    picks: "Подборки",
    subscriptions: "Подписки",
    season: "Сезон",
    leagues: "Лиги",
    topTournaments: "Топ турниры",
    quickLeagueNav: "Быстрый переход по лигам",
    catalog: "Каталог",
    currentLeague: "Текущая лига",
    changeLeague: "Сменить лигу",
    chooseLeague: "Выберите лигу",
    searchLeague: "Найти лигу",
    nothingFound: "Ничего не найдено",
    teams: "команд",
    language: "Язык",
    countryEngland: "Англия",
    countrySpain: "Испания",
    countryGermany: "Германия",
    countryItaly: "Италия",
    countryFrance: "Франция",
    countryEurope: "Европа",
    countryNationalTeams: "Сборные",
    countryPortugal: "Португалия",
    countryNetherlands: "Нидерланды",
    countryTurkey: "Турция",
    tournamentMatches: "Матчи турнира",
    resultsTitle: "Результаты",
    resultsLead:
      "Результаты сыгранных матчей. Нажмите на матч, чтобы открыть Match Center.",
    seasonUpper: "Сезон",
    loadingMatches: "Загружаем матчи...",
    errorPrefix: "Ошибка",
    noMatches: "Нет матчей для выбранных фильтров.",
    openMatchHint: "Нажми на матч, чтобы открыть Match Center.",
    loadingMoreRounds: "Загружаем следующие туры...",
    matchesCount: "матчей",
    calendarEyebrow: "Календарь турнира",
    scheduleTitle: "Расписание матчей",
    scheduleLead:
      "Предстоящие матчи турнира. Нажмите на матч, чтобы открыть Match Center.",
    loadingSchedule: "Загружаем расписание...",
    scheduleErrorPrefix: "Ошибка загрузки",
    noScheduledMatches: "Нет запланированных матчей для выбранного сезона.",
    loadingMatchAnalytics: "Загружаем аналитику по матчу...",
    lockedAnalyticsTitle: "Аналитика EdgeScore недоступна",
    lockedAnalyticsBody:
      "Откройте прогнозы, вероятности и value-сигналы по рынку.",
    goToPlans: "Перейти к тарифам",
    close: "Закрыть",
    bestPicksTitle: "Подборки ставок",
    allLeagues: "Все лиги",
    bestPicksLead:
      "Две рекомендации по матчам: исход и тотал 2.5 с пояснениями модели.",
    round: "Раунд",
    nearest: "Ближайший",
    noRounds: "нет раундов",
    loadingPremiumPicks: "Загружаем премиальные подборки...",
    lineupsLoading: "Загружаем составы...",
    startingLineups: "Стартовые составы",
    bench: "Запас",
    matchEvents: "События матча",
    homeSide: "Дома",
    awaySide: "Гости",
    assist: "ассист",
    standingsEyebrow: "Таблица турнира",
    playerStatsEyebrow: "Статистика игроков",
    scorers: "Бомбардиры",
    assists: "Ассисты",
    overall: "Общая",
    homeView: "Дома",
    awayView: "В гостях",
    groups: "Группы",
    playoff: "Плей-офф",
    team: "Команда",
    playedShort: "И",
    winsShort: "В",
    drawsShort: "Н",
    lossesShort: "П",
    goalsShort: "М",
    pointsShort: "О",
    noData: "Нет данных",
    points: "очков",
    tableSubtitle:
      "Позиции команд, очки и форма в выбранном сезоне. Нажмите на команду, чтобы открыть детальную аналитику.",
    tableHint:
      "Форма — последние 5 матчей. Кликни на команду, чтобы открыть подробную аналитику.",
    scorersSubtitle:
      "Топ бомбардиров выбранной лиги и сезона. Нажмите на игрока, чтобы открыть детальную статистику.",
    assistsSubtitle:
      "Топ ассистентов выбранной лиги и сезона. Нажмите на игрока, чтобы открыть детальную статистику.",
    groupedTableSubtitle:
      "Групповой этап разбит на отдельные компактные таблицы.",
    playoffSubtitle:
      "Турнирная сетка плей-офф по стадиям, суммарному счету и исходу пары.",
    dataLoading: "Загрузка данных...",
    player: "Игрок",
    goals: "Голы",
    penalties: "Пенальти",
    stage: "Стадия",
    todayEyebrow: "Обзор дня",
    todayTitle: "Что важно сегодня",
    todayLead:
      "Live-матчи, ближайшие игры и самый быстрый вход в EdgeScore.",
    matchOfTheDay: "Матч дня",
    bestSignalToday: "Лучший сигнал дня",
    livePriority: "Сейчас в лайве",
    upcomingPriority: "Ближайший фокус",
    openMatchCenter: "Открыть Match Center",
    liveNow: "Live сейчас",
    upcomingSoon: "Скоро начнутся",
    topLeaguesShort: "Топ-лиги",
    openResults: "Открыть результаты",
    openSchedule: "Открыть календарь",
    openPicks: "Открыть подборки",
    openTable: "Открыть таблицу",
    jumpIn: "Быстрый вход",
    noLiveMatches: "Сейчас нет live-матчей.",
    noUpcomingMatches: "В этом окне нет ближайших матчей.",
    viewAll: "Смотреть все",
    matchCenter: "Match Center",
    quickActions: "Быстрые действия",
    productShortAbout:
      "Быстрая футбольная аналитика с фокусом на матчах, которые стоит открыть прямо сейчас.",
    recentLeagues: "Недавние лиги",
    favoriteTeams: "Избранные команды",
    favoriteLeagues: "Избранные лиги",
    favoriteMatches: "Избранные матчи",
    noFavoriteTeams: "Пока нет избранных команд.",
    noFavoriteLeagues: "Пока нет избранных лиг.",
    noFavoriteMatches: "Пока нет избранных матчей.",
    recentMatches: "Недавно открывали",
    noRecentMatches: "Пока нет недавно открытых матчей.",
    bestPicksToday: "Лучшие пики сегодня",
    noBestPicksToday: "Для этого окна пока нет пиков.",
    evShort: "EV",
    oddsShort: "Кэф",
    noRecentLeagues: "Пока нет недавних лиг.",
    openLeague: "Открыть лигу",
    account: "Аккаунт",
    accountOverview: "Обзор",
    favoritesTab: "Избранное",
    subscriptionsTab: "Подписки",
    backHomeShort: "На главную",
    accountClosed: "Доступ закрыт",
    accountClosedBody: "Войдите, чтобы открыть личный кабинет.",
    signInAction: "Войти",
    unnamed: "Без названия",
    openCard: "Перейти в карточку",
    remove: "Удалить",
    removeFromFavoritesConfirm: "Удалить из избранного?",
    favoritesSectionEyebrow: "Избранное",
    teamsAndPlayers: "Команды и игроки",
    favoritesAlwaysReady: "Команды и игроки, которые всегда под рукой.",
    favoriteSchedule: "Календарь избранных",
    favoriteResults: "Результаты избранных",
    teamsLabel: "Команды",
    matchesLabel: "Матчи",
    playersLabel: "Игроки",
    noFavoriteTeamsBody: "Вы ещё не добавили команды в избранное. Добавляйте команды и следите за их формой и результатами.",
    noFavoriteMatchesBody: "Вы ещё не добавили матчи в избранное. Сохраняйте матчи, чтобы быстро к ним возвращаться.",
    noFavoritePlayersBody: "Вы ещё не добавили игроков в избранное. Добавляйте игроков и следите за их формой и результатами.",
    favoritesTotal: "Избранное",
    goToFavorites: "Перейти в избранное",
    activity: "Активность",
    registrationDateLead: "Дата регистрации в EdgeScore.",
    edgeScoreInsights: "Инсайты EdgeScore",
    edgeScoreInsightsLead: "Получайте объяснения прогнозов и факторов.",
    openInsights: "Открыть инсайты",
    quickLinks: "Быстрые переходы",
    matchResults: "Результаты матчей",
    scheduleAndPredictions: "Календарь и прогнозы",
    picksAndBestBets: "Подборки и лучшие ставки",
    aboutAndContacts: "О проекте и контакты",
    verifiedEmail: "Email подтверждён",
    verifyEmailNeeded: "Нужно подтвердить email",
    noSubscription: "Без подписки",
    teamsCountLabel: "команды",
    matchesCountLabel: "матча",
    playersCountLabel: "игрока",
    saveMatch: "Сохранить матч",
    removeMatch: "Убрать матч",
    saveLeague: "Сохранить лигу",
    removeLeague: "Убрать лигу",
    leagueSaved: "Лига сохранена",
    matchSaved: "Сохранен",
    signIn: "Вход в аккаунт",
    signUp: "Регистрация",
    profile: "Профиль",
    logOut: "Выйти",
    loginTitle: "Вход",
    loginCardTitle: "Вход в аккаунт",
    registerTitle: "Регистрация",
    backHome: "На главную",
    email: "Email",
    emailPlaceholder: "Введите email",
    passwordPlaceholder: "Введите пароль",
    passwordMinPlaceholder: "Минимум 8 символов",
    password: "Пароль",
    username: "Имя пользователя",
    usernamePlaceholder: "Введите имя пользователя",
    confirmPassword: "Подтвердите пароль",
    confirmPasswordPlaceholder: "Повторите пароль",
    loginSubmit: "Войти",
    loginSubmitting: "Вход...",
    registerSubmit: "Зарегистрироваться",
    registerSubmitting: "Регистрация...",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    registration: "Регистрация",
    registrationSuccess: "Регистрация успешна!",
    registrationSuccessBody:
      "Проверьте ваш email для подтверждения аккаунта. После подтверждения вы сможете войти в систему.",
    redirectingToLogin: "Перенаправление на страницу входа через несколько секунд...",
    passwordsDoNotMatch: "Пароли не совпадают",
    passwordTooShort: "Пароль должен содержать минимум 8 символов",
    loginFailed: "Ошибка входа",
    registrationFailed: "Ошибка регистрации",
    footballAnalytics: "Football Analytics",
    loginLead: "Используйте email и пароль, чтобы войти в профиль EdgeScore.",
    registerLead: "Создайте аккаунт, чтобы открыть аналитику, инсайты и премиальные подборки.",
    aboutProject: "О проекте",
    aboutLead:
      "Платформа футбольной аналитики, которая помогает быстрее понимать матч, форму команд и силу рыночного сигнала.",
    whatIsEdgescore: "Что такое EdgeScore",
    whatIsEdgescoreText:
      "EdgeScore — аналитическая платформа по футболу. Сервис собирает статистику матчей, формы команд, xG и рыночные коэффициенты, чтобы показывать более понятную картину матча и подсвечивать интересные сценарии.",
    howItWorks: "Как это работает",
    howItWorksText:
      "Модель оценивает силу сторон, темп игры, структуру моментов и расхождения с линией букмекера. На основе этого формируются сигналы по исходам, тоталам и объяснения, почему матч выглядит именно так.",
    whatUserGets: "Что получает пользователь",
    whatUserGetsText:
      "Результаты, календарь, инсайты, карточки команд и игроков, сравнение формы, очные встречи и подборки матчей. Сервис создан как рабочий инструмент для анализа, а не как витрина с сухими числами.",
    importantToKnow: "Важно понимать",
    importantToKnowText:
      "EdgeScore — это аналитика и модельная оценка, а не обещание результата. Любой сигнал — это вероятностный сценарий, а не гарантия. Решение пользователь принимает сам.",
    contacts: "Контакты",
    contactLead:
      "Если хочешь связаться по вопросам проекта, сотрудничества или обратной связи по продукту, используй этот адрес.",
    loading: "Загрузка...",
  },
};

function getInitialLanguage() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "ru" || stored === "en") return stored;
  } catch {}
  return "en";
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(getInitialLanguage);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {}
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
    }
  }, [lang]);

  const value = useMemo(
    () => ({
      lang,
      language: lang,
      setLang,
      t: (key) => DICTIONARY[lang]?.[key] ?? DICTIONARY.en[key] ?? key,
    }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
