INSERT INTO dm.sales_delivery_tracking_domestic
(
	delivery_number_initial,					-- SD.000001 "Исходная поставка"
	delivery_number_sales,						-- SD.000002 "Продажная поставка"
	delivery_number_of_producer_plant,			-- SD.000003 "Номер поставки завода производителя"
	batch,										-- SD.000004 "Партия"
	sales_order_in_shipment,					-- SD.000005 "Заказ ЦК в отгрузке"
	plant_producer_code,						-- SD.000006 "Завод (код)"
	plant_producer_name,						-- SD.000007 "Завод"
	dt_shipment,								-- SD.000010 "Дата отгрузки"
	material_aggr_name,							-- SD.000016 "Материал"
	material_group_code,						-- SD.000017 "Группа материалов"
	shipment_market_code,						-- SD.000018 "Рынок в отгрузке (код)"
	shipment_market_name,						-- SD.000019 "Рынок в отгрузке"
	transport_type_at_plant_code,				-- SD.000025 "Тип вагона на заводе (код)"
	transport_type_at_plant_name,				-- SD.000026 "Тип вагона на заводе"
	transport_railcar_type_code,				-- SD.000028 "Тип вагона (код)"
	transport_railcar_type_name,				-- SD.000029 "Тип вагона"
	weight_gross,								-- SD.000031 "Вес брутто"
	weight_net,									-- SD.000032 "Вес нетто"
	weight_net_with_wirerod,					-- SD.000033 "Вес Н&K"
	sales_order,								-- SD.000123 "Заказ ЦК"
	material_code,								-- SD.000143 "Номер материала"
	material_shape_name_full,					-- SD.000180 "Форма"
	material_name,								-- SD.000200 "Наименование материала"
	finish_good_group_code,						-- SD.000257 "Группа продукции"
	warehouse_shipment_type_name,				-- SD.000489 "СВХ"
	dt_shipment_yyyymm							-- SD.000893 "Месяц Дата отгрузки с завода"
)
SELECT
	delivery_number_initial,					-- SD.000001 "Исходная поставка"
	delivery_number_sales,						-- SD.000002 "Продажная поставка"
	delivery_number_of_producer_plant,			-- SD.000003 "Номер поставки завода производителя"
	batch,										-- SD.000004 "Партия"
	sales_order_in_shipment,					-- SD.000005 "Заказ ЦК в отгрузке"
	plant_producer_code,						-- SD.000006 "Завод (код)"
	plant_producer_name,						-- SD.000007 "Завод"
	dt_shipment,								-- SD.000010 "Дата отгрузки"
	material_aggr_name,							-- SD.000016 "Материал"
	material_group_code,						-- SD.000017 "Группа материалов"
	shipment_market_code,						-- SD.000018 "Рынок в отгрузке (код)"
	shipment_market_name,						-- SD.000019 "Рынок в отгрузке"
	transport_type_at_plant_code,				-- SD.000025 "Тип вагона на заводе (код)"
	transport_type_at_plant_name,				-- SD.000026 "Тип вагона на заводе"
	transport_railcar_type_code,				-- SD.000028 "Тип вагона (код)"
	transport_railcar_type_name,				-- SD.000029 "Тип вагона"
	weight_gross,								-- SD.000031 "Вес брутто"
	weight_net,									-- SD.000032 "Вес нетто"
	weight_net_with_wirerod,					-- SD.000033 "Вес Н&K"
	sales_order,								-- SD.000123 "Заказ ЦК"
	material_code,								-- SD.000143 "Номер материала"
	material_shape_name_full,					-- SD.000180 "Форма"
	material_name,								-- SD.000200 "Наименование материала"
	finish_good_group_code,						-- SD.000257 "Группа продукции"
	warehouse_shipment_type_name,				-- SD.000489 "СВХ"
	to_char(dt_shipment, 'yyyy.mm') 				-- SD.000893 "Месяц Дата отгрузки с завода"
FROM dm_calc.sd_sales_main_scm ssms
WHERE shipment_market_code = '3'			--где SD.000018 "Рынок в отгрузке (код)" = "3"
;