INSERT INTO STG."ZTLE_RAILCN"
( "MANDT", "ID", "POS", "TYPE_LOAD", "CONTAINER", "NUMNAKL", "DATEOT", "CAR_NUM", "ZDKODSTFR", "TRANS_KN", "TRANS_DATE", "BORDER_KN", "ZDKODSTTO", "WERKS", "WERKS_NAME", "GRADE", "MATNR", "ETSNG", "WEIGHT", "WEIGHT_BR", "RF_DATE", "RF_NUMNAKL", "VBELN", "DTL_VBELN", "DTL_TKNUM", "DTL_FKNUM", "VBELN_LE05", "VBELN_LE35", "VBELN_LE30", "ERDAT", "ERZET", "ERNAM", "AEDAT", "AEZET", "AENAM", "FORWARDER", "MBLNR_MM", "BELNR_MM", "BUZEI_MM", "RN")
SELECT "MANDT", "ID", "POS", "TYPE_LOAD", "CONTAINER", "NUMNAKL", "DATEOT", "CAR_NUM", "ZDKODSTFR", "TRANS_KN", "TRANS_DATE", "BORDER_KN", "ZDKODSTTO", "WERKS", "WERKS_NAME", "GRADE", "MATNR", "ETSNG", "WEIGHT", "WEIGHT_BR", "RF_DATE", "RF_NUMNAKL", "VBELN", "DTL_VBELN", "DTL_TKNUM", "DTL_FKNUM", "VBELN_LE05", "VBELN_LE35", "VBELN_LE30", "ERDAT", "ERZET", "ERNAM", "AEDAT", "AEZET", "AENAM", "FORWARDER", "MBLNR_MM", "BELNR_MM", "BUZEI_MM", "RN"
FROM raw_ext."ZTLE_RAILCN_READ";

