INSERT INTO stg."BSE_CLR"
SELECT "MANDT", "BUKRS_CLR", "BELNR_CLR", "GJAHR_CLR", "INDEX_CLR", "AGZEI", "AGBUZ", "WAERS", "CLRIN", "BUKRS", "BELNR", "GJAHR", "BUZEI", "SHKZG", "DMBTR", "DMBE2", "DMBE3", "WRBTR", "DIFHW", "DIFH2", "DIFH3", "DIFFW", "SKNTO", "SKNT2", "SKNT3", "WSKTO", "BDIFF", "BDIF2", "BDIF3", "RDIFF", "RDIF2", "RDIF3", "KOART", "UMSKZ", "UZAWE", "RN"
FROM raw_ext."BSE_CLR_READ";