Gather Motion 6:1  (slice9; segments: 6)  (cost=0.00..28860288.94 rows=341255441 width=644)
  ->  Result  (cost=0.00..28209041.61 rows=56875907 width=644)
        ->  Hash Left Join  (cost=0.00..28172413.52 rows=56875907 width=1086)
              Hash Cond: ((fixed_asset_operations.asset_movement_type_code)::text = (fixed_asset_movement_type_texts.fixed_asset_movement_type_code)::text)
              ->  Hash Left Join  (cost=0.00..27932824.73 rows=28437954 width=1041)
                    Hash Cond: ((fixed_asset_operations.depreciation_cost_center_code)::text = (cost_center.cost_center_code)::text)
                    Join Filter: ((fixed_asset_operations.dt_posting >= cost_center.dt_valid_from) AND (fixed_asset_operations.dt_posting <= cost_center.dt_valid_to))
                    ->  Hash Left Join  (cost=0.00..27799228.31 rows=28437954 width=989)
                          Hash Cond: ((fixed_asset_operations.depreciation_internal_order_code)::text = (order_controlling.order_code)::text)
                          ->  Hash Left Join  (cost=0.00..27689286.86 rows=14218977 width=936)
                                Hash Cond: ((sales_document_counterparty_role.personnel_code)::text = (personnel_main_data.employee_code)::text)
                                Join Filter: ((fixed_asset_operations.dt_posting >= personnel_main_data.dt_valid_from) AND (fixed_asset_operations.dt_posting <= personnel_main_data.dt_valid_to))
                                ->  Hash Left Join  (cost=0.00..27628776.39 rows=12561952 width=885)
                                      Hash Cond: ((invoice_realization.payee_or_payer_code)::text = (counterparty.counterparty_code)::text)
                                      ->  Hash Left Join  (cost=0.00..27584344.75 rows=6280976 width=840)
                                            Hash Cond: (((fixed_asset_operations.unit_balance_code)::text = (unit_balance.unit_balance_code)::text) AND ((fixed_asset_operations.asset_main_code)::text = ("substring"((invoice_realization_position.material_code)::text, 3))))
                                            ->  Redistribute Motion 6:6  (slice3; segments: 6)  (cost=0.00..27344246.98 rows=6280976 width=814)
                                                  Hash Key: fixed_asset_operations.unit_balance_code, fixed_asset_operations.asset_main_code
                                                  ->  Hash Left Join  (cost=0.00..27328244.19 rows=6280976 width=814)
                                                        Hash Cond: ((CASE WHEN ((settings_and_parameters_sap.parameter_code)::text = 'BWASL_L'::text) THEN '3'::text WHEN ((settings_and_parameters_sap.parameter_code)::text = 'BWASL_SE'::text) THEN '5'::text WHEN ((settings_and_parameters_sap.parameter_code)::text = 'BWASL_SI'::text) THEN '8'::text WHEN ((settings_and_parameters_sap.parameter_code)::text = 'BWASL_TR'::text) THEN '1'::text ELSE NULL::text END) = (disposal_type_texts.disposal_type_code)::text)
                                                        ->  Hash Join  (cost=0.00..27305809.03 rows=6280976 width=789)
                                                              Hash Cond: (((fixed_asset_main.unit_balance_code)::text = (fixed_asset_operations.unit_balance_code)::text) AND ((fixed_asset_main.asset_main_code)::text = (fixed_asset_operations.asset_main_code)::text) AND ((fixed_asset_main.asset_sub_code)::text = (fixed_asset_operations.asset_sub_code)::text) AND ((fixed_asset_main.valuation_area_code)::text = (fixed_asset_operations.valuation_area_code)::text))
                                                              Join Filter: ((fixed_asset_operations.dt_posting >= fixed_asset_main.dt_valid_from) AND (fixed_asset_operations.dt_posting <= fixed_asset_main.dt_valid_to))
                                                              ->  Seq Scan on fixed_asset_main  (cost=0.00..4648.99 rows=6280976 width=570)
                                                              ->  Hash  (cost=27151289.91..27151289.91 rows=15167384 width=235)
                                                                    ->  Append  (cost=0.00..27151289.91 rows=15167384 width=235)
                                                                          ->  Result  (cost=0.00..27110432.97 rows=14482070 width=235)
                                                                                ->  Redistribute Motion 6:6  (slice1; segments: 6)  (cost=0.00..27107029.68 rows=14482070 width=208)
                                                                                      Hash Key: fixed_asset_operations.unit_balance_code, fixed_asset_operations.asset_main_code, fixed_asset_operations.asset_sub_code, fixed_asset_operations.valuation_area_code
                                                                                      ->  Nested Loop Left Join  (cost=0.00..27097601.27 rows=14482070 width=208)
                                                                                            Join Filter: (((fixed_asset_operations.asset_movement_type_code)::text >= (settings_and_parameters_sap.range_low_value)::text) AND ((fixed_asset_operations.asset_movement_type_code)::text <= (COALESCE(settings_and_parameters_sap.range_high_value, settings_and_parameters_sap.range_low_value))::text))
                                                                                            ->  Seq Scan on fixed_asset_operations  (cost=0.00..1970.02 rows=1854703 width=203)
                                                                                                  Filter: ((dt_posting >= '2025-01-01'::date) AND (is_anlc IS NULL))
                                                                                            ->  Seq Scan on settings_and_parameters_sap  (cost=0.00..510.56 rows=58 width=21)
                                                                                                  Filter: (((abap_program_code)::text = 'ZFI5668M'::text) AND (NOT (range_sign_code IS NULL)))
                                                                          ->  Result  (cost=0.00..37292.61 rows=685314 width=294)
                                                                                ->  Result  (cost=0.00..37292.61 rows=685314 width=294)
                                                                                      ->  Result  (cost=0.00..37091.13 rows=685314 width=82)
                                                                                            Filter: ((row_number() OVER (?)) = 1)
                                                                                            ->  WindowAgg  (cost=0.00..37034.76 rows=1713285 width=90)
                                                                                                  Partition By: fixed_asset_cost_and_depreciation.unit_balance_code, fixed_asset_cost_and_depreciation.asset_main_code, fixed_asset_cost_and_depreciation.asset_sub_code, fixed_asset_cost_and_depreciation.valuation_area_code
                                                                                                  Order By: fixed_asset_cost_and_depreciation.dt_report
                                                                                                  ->  Sort  (cost=0.00..36887.42 rows=1713285 width=86)
                                                                                                        Sort Key: fixed_asset_cost_and_depreciation.unit_balance_code, fixed_asset_cost_and_depreciation.asset_main_code, fixed_asset_cost_and_depreciation.asset_sub_code, fixed_asset_cost_and_depreciation.valuation_area_code, fixed_asset_cost_and_depreciation.dt_report
                                                                                                        ->  Redistribute Motion 6:6  (slice2; segments: 6)  (cost=0.00..19587.03 rows=1713285 width=86)
                                                                                                              Hash Key: fixed_asset_cost_and_depreciation.unit_balance_code, fixed_asset_cost_and_depreciation.asset_main_code, fixed_asset_cost_and_depreciation.asset_sub_code, fixed_asset_cost_and_depreciation.valuation_area_code
                                                                                                              ->  Hash Join  (cost=0.00..19125.85 rows=1713285 width=86)
                                                                                                                    Hash Cond: (((fixed_asset_cost_and_depreciation.unit_balance_code)::text = (fixed_asset_lend_lease.unit_balance_code)::text) AND ((fixed_asset_cost_and_depreciation.asset_main_code)::text = (fixed_asset_lend_lease.asset_main_code)::text) AND ((fixed_asset_cost_and_depreciation.asset_sub_code)::text = (fixed_asset_lend_lease.asset_sub_code)::text))
                                                                                                                    Join Filter: (fixed_asset_cost_and_depreciation.dt_report <= fixed_asset_lend_lease.dt_lend_lease_posting)
                                                                                                                    ->  Seq Scan on fixed_asset_cost_and_depreciation  (cost=0.00..11317.02 rows=8395263 width=82)
                                                                                                                          Filter: (dt_report >= '2025-01-01'::date)
                                                                                                                    ->  Hash  (cost=483.51..483.51 rows=533417 width=26)
                                                                                                                          ->  Seq Scan on fixed_asset_lend_lease  (cost=0.00..483.51 rows=533417 width=26)
                                                        ->  Hash  (cost=431.00..431.00 rows=9 width=27)
                                                              ->  Seq Scan on disposal_type_texts  (cost=0.00..431.00 rows=9 width=27)
                                                                    Filter: ((language_code)::text = 'R'::text)
                                            ->  Hash  (cost=194539.94..194539.94 rows=3748043 width=57)
                                                  ->  Redistribute Motion 6:6  (slice8; segments: 6)  (cost=0.00..194539.94 rows=3748043 width=57)
                                                        Hash Key: unit_balance.unit_balance_code, ("substring"((invoice_realization_position.material_code)::text, 3))
                                                        ->  Result  (cost=0.00..193871.25 rows=3748043 width=57)
                                                              ->  Result  (cost=0.00..193871.25 rows=3748043 width=57)
                                                                    ->  Result  (cost=0.00..193282.81 rows=3748043 width=64)
                                                                          Filter: (((row_number() OVER (?)) = 1) AND (NOT (unit_balance.unit_balance_code IS NULL)))
                                                                          ->  WindowAgg  (cost=0.00..192666.26 rows=9370106 width=72)
                                                                                Partition By: invoice_realization_position.material_code
                                                                                Order By: invoice_realization.dt_billing_document
                                                                                ->  Sort  (cost=0.00..192029.09 rows=9370106 width=68)
                                                                                      Sort Key: invoice_realization_position.material_code, invoice_realization.dt_billing_document
                                                                                      ->  Redistribute Motion 6:6  (slice7; segments: 6)  (cost=0.00..108359.41 rows=9370106 width=68)
                                                                                            Hash Key: invoice_realization_position.material_code
                                                                                            ->  Result  (cost=0.00..106365.07 rows=9370106 width=68)
                                                                                                  ->  WindowAgg  (cost=0.00..106365.07 rows=9370106 width=68)
                                                                                                        Partition By: invoice_realization_position.material_code, invoice_realization.invoice_realization_code
                                                                                                        ->  Sort  (cost=0.00..106365.07 rows=9370106 width=75)
                                                                                                              Sort Key: invoice_realization_position.material_code, invoice_realization.invoice_realization_code
                                                                                                              ->  Redistribute Motion 6:6  (slice6; segments: 6)  (cost=0.00..14082.33 rows=9370106 width=75)
                                                                                                                    Hash Key: invoice_realization_position.material_code, invoice_realization.invoice_realization_code
                                                                                                                    ->  Hash Left Join  (cost=0.00..11882.70 rows=9370106 width=75)
                                                                                                                          Hash Cond: ((invoice_realization_position.sales_document_code)::text = (sales_contract_header.sales_contract_code)::text)
                                                                                                                          ->  Hash Left Join  (cost=0.00..6527.39 rows=4021540 width=77)
                                                                                                                                Hash Cond: ("left"((invoice_realization_position.material_code)::text, 2) = (unit_balance.fixed_asset_material_prefix_code)::text)
                                                                                                                                ->  Hash Right Join  (cost=0.00..4998.11 rows=65631 width=72)
                                                                                                                                      Hash Cond: ((sales_document_counterparty_role.sales_document_code)::text = (invoice_realization_position.sales_document_code)::text)
                                                                                                                                      Join Filter: (((sales_document_counterparty_role.sales_document_position_code)::text = (invoice_realization_position.sales_document_position_code)::text) OR ((sales_document_counterparty_role.sales_document_position_code)::text = '000000'::text))
                                                                                                                                      ->  Seq Scan on sales_document_counterparty_role  (cost=0.00..2634.33 rows=1552991 width=27)
                                                                                                                                            Filter: ((counterparty_role_code)::text = 'VE'::text)
                                                                                                                                      ->  Hash  (cost=1692.24..1692.24 rows=50112 width=70)
                                                                                                                                            ->  Redistribute Motion 6:6  (slice5; segments: 6)  (cost=0.00..1692.24 rows=50112 width=70)
                                                                                                                                                  Hash Key: invoice_realization_position.sales_document_code
                                                                                                                                                  ->  Hash Join  (cost=0.00..1681.26 rows=50112 width=70)
                                                                                                                                                        Hash Cond: ((invoice_realization.invoice_realization_code)::text = (invoice_realization_position.invoice_realization_code)::text)
                                                                                                                                                        ->  Seq Scan on invoice_realization  (cost=0.00..490.53 rows=845594 width=26)
                                                                                                                                                        ->  Hash  (cost=909.63..909.63 rows=50112 width=55)
                                                                                                                                                              ->  Redistribute Motion 6:6  (slice4; segments: 6)  (cost=0.00..909.63 rows=50112 width=55)
                                                                                                                                                                    Hash Key: invoice_realization_position.invoice_realization_code
                                                                                                                                                                    ->  Seq Scan on invoice_realization_position  (cost=0.00..901.01 rows=50112 width=55)
                                                                                                                                                                          Filter: ((sales_document_position_type_code)::text = ANY ('{ZAOS,ZAKT}'::text[]))
                                                                                                                                ->  Hash  (cost=431.04..431.04 rows=487 width=8)
                                                                                                                                      ->  Seq Scan on unit_balance  (cost=0.00..431.04 rows=487 width=8)
                                                                                                                          ->  Hash  (cost=1499.90..1499.90 rows=917402 width=20)
                                                                                                                                ->  Append  (cost=0.00..1499.90 rows=917402 width=20)
                                                                                                                                      ->  Seq Scan on sales_contract_header  (cost=0.00..563.78 rows=689787 width=20)
                                                                                                                                      ->  Seq Scan on sales_order_header  (cost=0.00..452.17 rows=222469 width=20)
                                                                                                                                      ->  Seq Scan on sales_proposal_header  (cost=0.00..431.47 rows=5147 width=20)
                                      ->  Hash  (cost=573.56..573.56 rows=435628 width=56)
                                            ->  Seq Scan on counterparty  (cost=0.00..573.56 rows=435628 width=56)
                                ->  Hash  (cost=502.71..502.71 rows=623814 width=68)
                                      ->  Seq Scan on personnel_main_data  (cost=0.00..502.71 rows=623814 width=68)
                          ->  Hash  (cost=488.07..488.07 rows=258771 width=65)
                                ->  Seq Scan on order_controlling  (cost=0.00..488.07 rows=258771 width=65)
                    ->  Hash  (cost=433.76..433.76 rows=32745 width=70)
                          ->  Seq Scan on cost_center  (cost=0.00..433.76 rows=32745 width=70)
              ->  Hash  (cost=431.39..431.39 rows=651 width=49)
                    ->  Seq Scan on fixed_asset_movement_type_texts  (cost=0.00..431.39 rows=651 width=49)
                          Filter: ((language_code)::text = 'R'::text)
Optimizer: Pivotal Optimizer (GPORCA)
