insert into stg."/RUSAL/REDIRECT"
("MANDT", "TRAID", "BOLNR1", "LFDAT1", "CHANGE_TYPE", "BOLNR2", "LFDAT2", "KNANF2", "KNEND2", "VSART2", "IDX", "ERDAT", "ERNAM", "STATUS_EXP", "STATUS_CALC", "ROUTE2", "KNANF1", "ETSNG", "ROUTE1", "KNANF3", "KNEND3", "RN")
SELECT "MANDT", "TRAID", "BOLNR1", "LFDAT1", "CHANGE_TYPE", "BOLNR2", "LFDAT2", "KNANF2", "KNEND2", "VSART2", "IDX", "ERDAT", "ERNAM", "STATUS_EXP", "STATUS_CALC", "ROUTE2", "KNANF1", "ETSNG", "ROUTE1", "KNANF3", "KNEND3", "RN"
FROM raw_ext."/RUSAL/REDIRECT_READ";