INSERT INTO stg."/RUSAL/MIRR"
("MANDT", "AWTYP", "AWKEY", "BUKRS", "BELNR", "GJAHR", "BUDAT", "BLART", "LIFNR", "AWKEY_ST", "STBLG", "STJAH", "BUDAT_ST", "STGRD", "MIRR_TYPE", "INCO1_R", "BRAN1_R", "RN")
SELECT "MANDT", "AWTYP", "AWKEY", "BUKRS", "BELNR", "GJAHR", "BUDAT", "BLART", "LIFNR", "AWKEY_ST", "STBLG", "STJAH", "BUDAT_ST", "STGRD", "MIRR_TYPE", "INCO1_R", "BRAN1_R", "RN"
FROM raw_ext."/RUSAL/MIRR_READ";