INSERT INTO stg."/RUSAL/OTMM_RV" ("MANDT", "MATNR", "WERKS", "POPERS", "POPERPO", "ID_VES", "MEINS", "UCHPRZV", "PRZV", "PORSORT", "PASSERV", "UCH_KNANF", "KNANF", "AVT_ZAHOD", "RN")
SELECT "MANDT", "MATNR", "WERKS", "POPERS", "POPERPO", "ID_VES", "MEINS", "UCHPRZV", "PRZV", "PORSORT", "PASSERV", "UCH_KNANF", "KNANF", "AVT_ZAHOD", "RN"
FROM raw_ext."/RUSAL/OTMM_RV_READ";
