INSERT INTO stg."/RUSAL/MIRP"
("MANDT", "AWTYP", "AWKEY", "ZBUKRS", "ZBELNR", "ZGJAHR", "ZBLART", "ZSTBLG", "ZSTJAH", "RN")
SELECT "MANDT", "AWTYP", "AWKEY", "ZBUKRS", "ZBELNR", "ZGJAHR", "ZBLART", "ZSTBLG", "ZSTJAH", "RN"
FROM raw_ext."/RUSAL/MIRP_READ";