insert into ods.map_delivery_document_attributes_keys_ral(
	delivery_code,
	dt_shipped_yyyymm,
	transport_departure_hub_code,
	transport_destination_hub_code,
	port_of_destination_code,
	transport_border_cross_hub_code,
	etsng_code,
	is_pickup_at_plant,
	material_code,
	sector_code,
	complected_train_code,
	shipment_type_code,
	transport_scheme_code, 
	forwarder_at_plant_code,
	is_transferrable_expenses,
	incoterms_plan_code,
	is_owned_by_rusal_code,
	load_waybill_documented_weight,  
	load_calculated_weight,
	carrying_capacity_for_tariff_planning_weight,
	complected_train_quantity_index_code,
	sales_order_code,
	sales_order_plant_code,
	dt_updated,
	is_container_owned_by_forwarder_code,
	is_platform_owned_by_forwarder_code,
	container_length_type_code,
	forwarder_at_railway_code,
	port_of_departure_code
)
select 
	tech_etl.util_text_to_null_validation("VBELN") as delivery_code,
	tech_etl.util_text_to_null_validation("PERIOD") as dt_shipped_yyyymm,
	tech_etl.util_text_to_null_validation("ZZKNOTA") as transport_departure_hub_code,
	tech_etl.util_text_to_null_validation("ZZKNOTZ3") as transport_destination_hub_code,
	tech_etl.util_text_to_null_validation("ZZPORTNOTRF") as port_of_destination_code,
	tech_etl.util_text_to_null_validation("ZZKNOTE_BRD") as transport_border_cross_hub_code,
	tech_etl.util_text_to_null_validation("ZZETSNG") as etsng_code,
	tech_etl.util_text_to_null_validation("PICKUP") as is_pickup_at_plant,
	tech_etl.util_text_to_null_validation("MATNR") as material_code,
	tech_etl.util_text_to_null_validation("ZZSPART") as sector_code,
	tech_etl.util_text_to_null_validation("ZZSET") as complected_train_code,
	tech_etl.util_text_to_null_validation("ZZVSART") as shipment_type_code,
	tech_etl.util_text_to_null_validation("SCHEME") as transport_scheme_code,
	tech_etl.util_text_to_null_validation("LIFNR_ZHD") as forwarder_at_plant_code,
	tech_etl.util_text_to_null_validation("ZTR_RECOV") as is_transferrable_expenses,
	tech_etl.util_text_to_null_validation("INCO1") as incoterms_plan_code,
	tech_etl.util_text_to_null_validation("HOME_VAGON") as is_owned_by_rusal_code,
	"VES_NAT" as load_waybill_documented_weight,
	"VES_RAS" as load_calculated_weight,
	"ZZGRUZ"::int2 as carrying_capacity_for_tariff_planning_weight,
	tech_etl.util_text_to_null_validation("ZZINDEX") as complected_train_quantity_index_code,
	tech_etl.util_text_to_null_validation("ZAKAZ_KL") as sales_order_code,
	tech_etl.util_text_to_null_validation("ZAKAZ_KL_L") as sales_order_plant_code,
	tech_etl.util_text_to_timestamp_validation("CRDATE", "CRTIME") as dt_updated,
	tech_etl.util_text_to_null_validation("ZZPR_CONT") as is_container_owned_by_forwarder_code,
	tech_etl.util_text_to_null_validation("ZZPR_PL") as is_platform_owned_by_forwarder_code,
	tech_etl.util_text_to_null_validation("ZZLENGTH") as container_length_type_code,
	tech_etl.util_text_to_null_validation("LIFNR_ZHD") as forwarder_at_railway_code,
	tech_etl.util_text_to_null_validation("ZZPORTRF") as port_of_departure_code
from stg."ZLE_SD3332M_DATA"
where 1=1
	and "PERIOD">='202001'  -- Инкремент обновления, по дате. После инициирующей, обновлять на согласованную глубину
;