INSERT INTO STG."ZLE_DOG_LIMIT"
( "MANDT", "EBELN", "WERKS", "KTWRT", "KTWRT_BALANCE", "SUM_AKT", "SUM_AKT_ACCEPTED", "SUM_TAP", "WAERS", "RN", "DTTM_INSERTED", "DTTM_UPDATED", "JOB_NAME", "DELETED_FLAG", "IS_ACTUAL")
SELECT  "MANDT", "EBELN", "WERKS", "KTWRT", "KTWRT_BALANCE", "SUM_AKT", "SUM_AKT_ACCEPTED", "SUM_TAP", "WAERS", "RN", now(), now(), 'airflow', false, true
FROM  RAW_EXT."ZLE_DOG_LIMIT_READ";