insert into ods."/rusal/perh_ral" (
	werks,
	id,
	noms,
	nomp,
	bedat,
	status_doc,
	lifnr,
	zlifnr,
	lifnr_pr,
	lifnr_pr1,
	comments,
	duedat,
	ernam,
	erdat,
	erzet,
	aenam,
	aedat,
	aezet,
	type2,
	waers,
	tap_sum,
	odo_user,
	odo_dfk_user,
	odo_date,
	accept,
	accept_name,
	accept_date,
	budat,
	duedatm,
	kor_akt,
	state,
	status_sver,
	status_sogl,
	status_uved,
	status_back_off,
	sverka_pass_date,
	aldor,
	blok_user,
	blok_date,
	rereg,
	respon,
	nofact2,
	recdt,
	invtp,
	edit_ztap,
	sogl_usnam,
	sogl_date,
	uved_ernam,
	uved_erdat,
	rcu_uname,
	rcu_date,
	rcu_time,
	vehicle
)
select
	tech_etl.util_text_to_null_validation(perh."WERKS") as werks,
	tech_etl.util_text_to_null_validation(perh."ID") as id,
	tech_etl.util_text_to_null_validation(perh."NOMS") as noms,
	tech_etl.util_text_to_null_validation(perh."NOMP") as nomp,
	tech_etl.util_text_to_date_validation(perh."BEDAT") as bedat,
	tech_etl.util_text_to_null_validation(perh."STATUS_DOC") as status_doc,
	tech_etl.util_text_to_null_validation(perh."LIFNR") as lifnr,
	tech_etl.util_text_to_null_validation(perh."ZLIFNR") as zlifnr,
	tech_etl.util_text_to_null_validation(perh."LIFNR_PR") as lifnr_pr,
	tech_etl.util_text_to_null_validation(perh."LIFNR_PR1") as lifnr_pr1,
	tech_etl.util_text_to_null_validation(perh."COMMENTS") as comments,
	tech_etl.util_text_to_date_validation(perh."DUEDAT") as duedat,
	tech_etl.util_text_to_null_validation(perh."ERNAM") as ernam,
	tech_etl.util_text_to_date_validation(perh."ERDAT") as erdat,
	tech_etl.util_text_to_time_validation(perh."ERZET") as erzet,
	tech_etl.util_text_to_null_validation(perh."AENAM") as aenam,
	tech_etl.util_text_to_date_validation(perh."AEDAT") as aedat,
	tech_etl.util_text_to_time_validation(perh."AEZET") as aezet,
	tech_etl.util_text_to_null_validation(perh."TYPE2") as type2,
	tech_etl.util_text_to_null_validation(perh."WAERS") as waers,
	perh."TAP_SUM" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as tap_sum,
	tech_etl.util_text_to_null_validation(perh."ODO_USER") as odo_user,
	tech_etl.util_text_to_null_validation(perh."ODO_DFK_USER") as odo_dfk_user,
	tech_etl.util_text_to_date_validation(perh."ODO_DATE") as odo_date,
	tech_etl.util_text_to_null_validation(perh."ACCEPT") as accept,
	tech_etl.util_text_to_null_validation(perh."ACCEPT_NAME") as accept_name,
	tech_etl.util_text_to_date_validation(perh."ACCEPT_DATE") as accept_date,
	tech_etl.util_text_to_date_validation(perh."BUDAT") as budat,
	tech_etl.util_text_to_null_validation(perh."DUEDATM") as duedatm,
	tech_etl.util_text_to_null_validation(perh."KOR_AKT") as kor_akt,
	tech_etl.util_text_to_null_validation(perh."STATE") as state,
	tech_etl.util_text_to_null_validation(perh."STATUS_SVER") as status_sver,
	tech_etl.util_text_to_null_validation(perh."STATUS_SOGL") as status_sogl,
	tech_etl.util_text_to_null_validation(perh."STATUS_UVED") as status_uved,
	tech_etl.util_text_to_null_validation(perh."STATUS_BACK_OFF") as status_back_off,
	tech_etl.util_text_to_date_validation(perh."SVERKA_PASS_DATE") as sverka_pass_date,
	tech_etl.util_text_to_null_validation(perh."ALDOR") as aldor,
	tech_etl.util_text_to_null_validation(perh."BLOK_USER") as blok_user,
	tech_etl.util_text_to_date_validation(perh."BLOK_DATE") as blok_date,
	tech_etl.util_text_to_null_validation(perh."REREG") as rereg,
	tech_etl.util_text_to_null_validation(perh."RESPON") as respon,
	tech_etl.util_text_to_null_validation(perh."NOFACT2") as nofact2,
	tech_etl.util_text_to_date_validation(perh."RECDT") as recdt,
	tech_etl.util_text_to_null_validation(perh."INVTP") as invtp,
	tech_etl.util_text_to_null_validation(perh."EDIT_ZTAP") as edit_ztap,
	tech_etl.util_text_to_null_validation(perh."SOGL_USNAM") as sogl_usnam,
	tech_etl.util_text_to_date_validation(perh."SOGL_DATE") as sogl_date,
	tech_etl.util_text_to_null_validation(perh."UVED_ERNAM") as ernam,
	tech_etl.util_text_to_date_validation(perh."UVED_ERDAT") as uved_erdat,
	tech_etl.util_text_to_null_validation(perh."RCU_UNAME") as rcu_uname,
	tech_etl.util_text_to_date_validation(perh."RCU_DATE") as rcu_date,
	tech_etl.util_text_to_time_validation(perh."RCU_TIME") as rcu_time,
	tech_etl.util_text_to_null_validation(perh."VEHICLE") as vehicle
from stg."/RUSAL/PERH" as perh
	left join dict_dds.currency_decimal_place_ral as dp			---джойн с TCURX RAL
		on dp.currency_code = perh."WAERS"
where "MANDT" = '400';