INSERT INTO stg."/RUSAL/PERZ"
("MANDT", "WERKS", "ID", "POS", "POSV", "ID_DOC", "POS_DOC", "BUKRS", "BELNR", "GJAHR", "VBELN", "POSNR", "BUDAT", "DOKSYS", "TYPE", "OBJSP", "KOR", "ALDOR", "CPUDT", "CPUTM", "RN")
SELECT "MANDT", "WERKS", "ID", "POS", "POSV", "ID_DOC", "POS_DOC", "BUKRS", "BELNR", "GJAHR", "VBELN", "POSNR", "BUDAT", "DOKSYS", "TYPE", "OBJSP", "KOR", "ALDOR", "CPUDT", "CPUTM", "RN"
FROM raw_ext."/RUSAL/PERZ_READ";