// frontend/src/constants/teamLogoMap.js
export const teamLogoMap = {
  "Arsenal": "/icons/team_logos/arsenal_fc.png",
  "Aston Villa": "/icons/team_logos/aston_villa_fc.png",
  "Atlético Madrid": "/icons/team_logos/club_atlético_de_madrid.png",
  "Atalanta": "/icons/team_logos/atalanta_bc.png",
  "Athletic Club": "/icons/team_logos/athletic_club.png",
  "Barcelona": "/icons/team_logos/fc_barcelona.png",
  "Betis": "/icons/team_logos/real_betis_balompié.png",
  "Bologna": "/icons/team_logos/bologna_fc_1909.png",
  "Bournemouth": "/icons/team_logos/afc_bournemouth.png",
  "Brentford": "/icons/team_logos/brentford_fc.png",
  "Brighton": "/icons/team_logos/brighton_&_hove_albion_fc.png",
  "Burnley": "/icons/team_logos/burnley_fc.png",
  "Cagliari": "/icons/team_logos/cagliari_calcio.png",
  "Celta Vigo": "/icons/team_logos/rc_celta_de_vigo.png",
  "Chelsea": "/icons/team_logos/chelsea_fc.png",
  "Cremonese": "/icons/team_logos/us_cremonese.png",
  "Como": "/icons/team_logos/como_1907.png",
  "Crystal Palace": "/icons/team_logos/crystal_palace_fc.png",
  "Elche": "/icons/team_logos/elche_cf.png",
  "Espanyol": "/icons/team_logos/rcd_espanyol_de_barcelona.png",
  "Everton": "/icons/team_logos/everton_fc.png",
  "Fiorentina": "/icons/team_logos/acf_fiorentina.png",
  "Fulham": "/icons/team_logos/fulham_fc.png",
  "Genoa": "/icons/team_logos/genoa_cfc.png",
  "Getafe": "/icons/team_logos/getafe_cf.png",
  "Girona": "/icons/team_logos/girona_fc.png",
  "Hellas Verona": "/icons/team_logos/hellas_verona_fc.png",
  "Inter": "/icons/team_logos/fc_internazionale_milano.png",
  "Juventus": "/icons/team_logos/juventus_fc.png",
  "Lazio": "/icons/team_logos/ss_lazio.png",
  "Leeds United": "/icons/team_logos/leeds_united_fc.png",
  "Lecce": "/icons/team_logos/us_lecce.png",
  "Levante": "/icons/team_logos/levante_ud.png",
  "Liverpool": "/icons/team_logos/liverpool_fc.png",
  "Mallorca": "/icons/team_logos/rcd_mallorca.png",
  "Manchester City": "/icons/team_logos/manchester_city_fc.png",
  "Manchester Utd": "/icons/team_logos/manchester_united_fc.png",
  "Milan": "/icons/team_logos/ac_milan.png",
  "Napoli": "/icons/team_logos/ssc_napoli.png",
  "Newcastle Utd": "/icons/team_logos/newcastle_united_fc.png",
  "Nott'ham Forest": "/icons/team_logos/nottingham_forest_fc.png",
  "Osasuna": "/icons/team_logos/ca_osasuna.png",
  "Oviedo": "/icons/team_logos/real_oviedo.png",
  "Parma": "/icons/team_logos/parma_calcio_1913.png",
  "Pisa": "/icons/team_logos/ac_pisa_1909.png",
  "Rayo Vallecano": "/icons/team_logos/rayo_vallecano_de_madrid.png",
  "Real Madrid": "/icons/team_logos/real_madrid_cf.png",
  "Real Sociedad": "/icons/team_logos/real_sociedad_de_fútbol.png",
  "Roma": "/icons/team_logos/as_roma.png",
  "Sassuolo": "/icons/team_logos/us_sassuolo_calcio.png",
  "Sevilla": "/icons/team_logos/sevilla_fc.png",
  "Sunderland": "/icons/team_logos/sunderland_afc.png",
  "Torino": "/icons/team_logos/torino_fc.png",
  "Tottenham": "/icons/team_logos/tottenham_hotspur_fc.png",
  "Udinese": "/icons/team_logos/udinese_calcio.png",
  "Valencia": "/icons/team_logos/valencia_cf.png",
  "Villarreal": "/icons/team_logos/villarreal_cf.png",
  "West Ham": "/icons/team_logos/west_ham_united_fc.png",
  "Wolves": "/icons/team_logos/wolverhampton_wanderers_fc.png",
  "Alavés": "/icons/team_logos/deportivo_alavés.png"
};
