insert into ods."ekko_ral"
select
	tech_etl.util_text_to_null_validation("EBELN") as ebeln,
	tech_etl.util_text_to_date_validation("AEDAT") as aedat,
	tech_etl.util_text_to_date_validation("BEDAT") as bedat,
	tech_etl.util_text_to_null_validation("BSART") as bsart,
	tech_etl.util_text_to_null_validation("BSTYP") as bstyp,
	tech_etl.util_text_to_null_validation("BUKRS") as bukrs,
	tech_etl.util_text_to_null_validation("EKGRP") as ekgrp,
	tech_etl.util_text_to_null_validation("EKORG") as ekorg,
	tech_etl.util_text_to_null_validation("FRGGR") as frggr,
	tech_etl.util_text_to_null_validation("FRGKE") as frgke,
	tech_etl.util_text_to_null_validation("FRGRL") as frgrl,
	tech_etl.util_text_to_null_validation("FRGSX") as frgsx,
	tech_etl.util_text_to_null_validation("FRGZU") as frgzu,
	tech_etl.util_text_to_null_validation("IHREZ") as ihrez,
	tech_etl.util_text_to_null_validation("INCO1") as inco1,
	tech_etl.util_text_to_null_validation("INCO2") as inco2,
	tech_etl.util_text_to_null_validation("KALSM") as kalsm,
	tech_etl.util_text_to_date_validation("KDATB") as kdatb,
	tech_etl.util_text_to_date_validation("KDATE") as kdate,
	tech_etl.util_text_to_null_validation("KNUMV") as knumv,
	"KTWRT" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as ktwrt,
	tech_etl.util_text_to_null_validation("LIFNR") as lifnr,
	tech_etl.util_text_to_null_validation("TELF1") as telf1,
	tech_etl.util_text_to_null_validation("UNSEZ") as unsez,
	tech_etl.util_text_to_null_validation("VERKF") as verkf,
	tech_etl.util_text_to_null_validation("WAERS") as waers,
	tech_etl.util_text_to_null_validation("ZTERM") as zterm,
	tech_etl.util_text_to_null_validation("ZURDOG") as zurdog,
	tech_etl.util_text_to_null_validation("ZZBANFN") as zzbanfn,
	tech_etl.util_text_to_null_validation("ZZBIZP") as zzbizp,
	tech_etl.util_text_to_null_validation("ZZBVTYP") as zzbvtyp,
	"ZZCOMERCIALLOAN" as zzcomercialloan,
	tech_etl.util_text_to_null_validation("ZZDOGKR") as zzdogkr,
	tech_etl.util_text_to_date_validation("ZZDTOTS1") as zzdtots1,
	tech_etl.util_text_to_date_validation("ZZDTOTS2") as zzdtots2,
	tech_etl.util_text_to_date_validation("ZZDTOTS3") as zzdtots3,
	tech_etl.util_text_to_date_validation("ZZDTOTS4") as zzdtots4,
	tech_etl.util_text_to_null_validation("ZZEBELN") as zzebeln,
	tech_etl.util_text_to_null_validation("ZZEDO") as zzedo,
	tech_etl.util_text_to_null_validation("ZZERNAM") as zzernam,
	tech_etl.util_text_to_null_validation("ZZIHREZ") as zzihrez,
	tech_etl.util_text_to_null_validation("ZZKNOTE") as zzknote,
	tech_etl.util_text_to_null_validation("ZZKONDM") as zzkondm,
	"ZZKTWRT" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as zzktwrt,
	tech_etl.util_text_to_null_validation("ZZKURS") as zzkurs,
	tech_etl.util_text_to_null_validation("ZZMWSKZ") as zzmwskz,
	tech_etl.util_text_to_null_validation("ZZNIOKRTXT") as zzniokrtxt,
	"ZZNOMORE" as zznomore,
	tech_etl.util_text_to_null_validation("ZZNUMPR") as zznumpr,
	"ZZONEPENALTY" as zzonepenalty,
	"ZZONEPENALTY1" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as zzonepenalty1,
	"ZZPENALTY" as zzpenalty,
	tech_etl.util_text_to_null_validation("ZZPENALTYREFRATE") as zzpenaltyrefrate,
	tech_etl.util_text_to_null_validation("ZZPPSKD") as zzppskd,
	tech_etl.util_text_to_null_validation("ZZQUOTA") as zzquota,
	tech_etl.util_text_to_null_validation("ZZRCODE") as zzrcode,
	tech_etl.util_text_to_null_validation("ZZRESP") as zzresp,
	tech_etl.util_text_to_null_validation("ZZSEGREP") as zzsegrep,
	tech_etl.util_text_to_null_validation("ZZSUM") as zzsum,
	tech_etl.util_text_to_null_validation("ZZTARIFF") as zztariff,
	tech_etl.util_text_to_null_validation("ZZTEMPID") as zztempid,
	"ZZTZR" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as zztzr,
	tech_etl.util_text_to_null_validation("ZZUNIDOC") as zzunidoc,
	tech_etl.util_text_to_null_validation("ZZUNIDOC_S") as zzunidoc_s,
	tech_etl.util_text_to_null_validation("ZZVBELN") as zzvbeln,
	tech_etl.util_text_to_null_validation("ZZVBELN_ZX") as zzvbeln_zx,
	tech_etl.util_text_to_null_validation("ZZZHDTARIF") as zzzhdtarif,
	tech_etl.util_text_to_null_validation("ERNAM") as ernam,
	tech_etl.util_text_to_null_validation("ADRNR") as adrnr,
	tech_etl.util_text_to_null_validation("DESCRIPTION") as description,
	tech_etl.util_text_to_null_validation("ZZCOSTR") as zzcostr,
	tech_etl.util_text_to_null_validation("ZZPAYDOX") as zzpaydox,
	tech_etl.util_text_to_null_validation("ZZPAYMENTRULE") as zzpaymentrule,
	tech_etl.util_text_to_null_validation("ZZKNANF_TERM") as zzknanf_term,
	tech_etl.util_text_to_null_validation("ZZPORT") as zzport,
	tech_etl.util_text_to_null_validation("KONNR") as konnr,
	tech_etl.util_text_to_null_validation("MEMORY") as memory
from stg."EKKO"
	left join dict_dds.currency_decimal_place_ral as dp			---джойн с TCURX RAL
		on dp.currency_code = "WAERS"
where "MANDT" = '400';