drop table if exists stg.s1c_debt_for_working_capital;

CREATE TABLE stg.s1c_debt_for_working_capital (
	sender varchar NULL,
	receiver varchar NULL,
	create_date_time timestamp NULL, ---СТГ сейчас это поле называется create_ddate_time, перегружать не стал инит ~20 минут 
	dt_report date NULL,
	database_code_1c varchar NULL,
	database_name_1c varchar NULL,
	unit_balance_mdm_code_1c varchar NULL,
	posting_uid_code_1c varchar NULL,
	invoice_registration_number varchar NULL,
	counterparty_role_name varchar NULL,
	debit_or_credit_name varchar NULL,
	accounting_document_descriprion_text varchar NULL,
	document_1c_code varchar NULL,
	responsibility_center_hfm_code varchar NULL,
	region_of_end_user_code varchar NULL,
	country_of_end_user_code varchar NULL,
	counterparty_mdm_code varchar NULL,
	counterparty_annual_turnover_amount numeric(20, 6) NULL,
	finish_goods_group_name varchar NULL,
	contract_number varchar NULL,
	paydox_document_url varchar NULL,
	contract_type_name varchar NULL,
	contract_amount numeric(20, 6) NULL,
	contract_currency_code varchar NULL,
	dt_contract_start date NULL,
	dt_contract_end date NULL,
	terms_of_payment_name varchar NULL,
	dt_overdue date NULL,
	debt_coverage_type_name varchar NULL,
	coverage_amount numeric(20, 6) NULL,
	coverage_currency_code varchar NULL,
	dt_debt date NULL,
	document_currency_code varchar NULL,
	debt_balance_document_currency_amount numeric(20, 6) NULL,
	debt_balance_rub_currency_amount numeric(20, 6) NULL,
	debt_balance_usd_currency_amount numeric(20, 6) NULL,
	debt_overdue_document_currency_amount numeric(20, 6) NULL,
	debt_overdue_rub_currency_amount numeric(20, 6) NULL,
	debt_overdue_usd_currency_amount numeric(20, 6) NULL,
	bank_receiver_name varchar NULL,
	receivable_claim_paydox_url varchar NULL,
	dt_receivable_claim date NULL,
	dt_claim_send_to_law_court date NULL,
	contract_supervisor_name varchar NULL,
	contract_supervisor_ad_login_code varchar NULL,
	general_ledger_account_code varchar NULL,
	general_ledger_account_name varchar NULL,
	dt_contract_registration date NULL,
	document_currency_amount numeric(20, 6) NULL,
	contract_supervisor_employee_1c_number varchar NULL,
	contract_supervisor_employee_sap_number varchar NULL,
	sales_market_code varchar NULL,
	sales_market_name varchar NULL,
	bad_debt_provision_amount numeric(20, 6) NULL,
	bad_debt_provision_currency_code varchar NULL,
	credit_limit_rub_currency_amount numeric(20, 6) NULL,
	dt_credit_limit_valid_to date NULL,
	paydox_credit_limit_url varchar NULL,
	insured_amount numeric(20, 6) NULL,
	insurance_currency_code varchar NULL,
	dt_insurance_valid_to date NULL,
	insurance_company_mdm_code varchar NULL,
	bank_guarantee_amount numeric(20, 6) NULL,
	bank_guarantee_currency_code varchar NULL,
	dt_bank_guarantee_valid_to date NULL,
	bank_guarantee_mdm_code varchar NULL,
	third_party_guarantee_amount numeric(20, 6) NULL,
	third_party_guarantee_currency_code varchar NULL,
	dt_third_party_guarantee_valid_to date NULL,
	third_party_guarantee_mdm_code varchar NULL,
	debt_balance_exchange_diff_rub_amount numeric(20, 6) NULL,
	debt_balance_exchange_diff_usd_amount numeric(20, 6) NULL,
	uuid varchar(60) NULL, 
	dt_insert timestamp
)
WITH (
	appendonly=true,
	orientation=column,
	compresstype=zstd,
	compresslevel=3
)
DISTRIBUTED by (uuid);