insert into dm.account_debt_for_working_capital_1c ( 
	dt,
	is_second_friday,
	unit_balance_code,
	fiscal_year,
	accounting_document_code,
	dt_debt,
	dt_overdue,
	dt_clearing,
	contract_number,
	counterparty_code,
	debit_or_credit,
	account_type,
	general_ledger_account_code,
	debt_balance_document_currency_amount,
	debt_balance_local_currency_amount,
	debt_balance_second_local_currency_amount,
	debt_balance_with_revaluation_diff_second_currency_amount,
	debt_balance_position_usd_amount,
	document_currency_code,
	local_currency_code,
	second_local_currency_code,
	accounting_document_type,
	accounting_document_type_name,
	position_line_item,
	reverse_document_code,
	reference_document_number,
	accounting_document_status_code,
	clearing_document_code,
	tax_code,
	position_line_item_text,
	special_general_ledger_indicator,
	dt_baseline_due_date_calculation,
	assignment_number,
	dt_accounting_document,
	plant_code,
	plant_name,
	general_ledger_account_full_name,
	unit_balance_name,
	counterparty_full_name,
	external_contract_number,
	dt_external_contract,
	contract_trader_code,
	contract_trader_name,
	terms_of_payment_code,
	terms_of_payment_name,
	responsibility_center_code,
	responsibility_center_name,
	budget_subtype_code,
	contract_supervisor_employee_number,
	contract_supervisor_name,
	purchase_or_sales_group_code,
	purchase_or_sales_group_name,
	funds_center_code,
	funds_center_name,
	debt_subposition_number,
	debt_subposition_local_currency_amount,
	debt_subposition_document_currency_amount,
	debt_subposition_second_local_currency_amount,
	is_debt_daily_calculated,
	country_code,
	counterparty_hfm_code,
	counterparty_mdm_code,
	is_related_party_tco,
	is_group_company_affiliated,
	is_related_party_rsbo,
	is_bankrupt,
	is_lawsuit_exist,
	is_fns_restriction_list_exist,
	document_currency_amount,
	local_currency_amount,
	second_local_currency_amount,
	counterparty_tin_code,
	reverse_document_fiscal_year,
	reason_for_reversal,
	debt_balance_subposition_document_currency_amount,
	debt_balance_subposition_local_currency_amount,
	debt_balance_subposition_second_local_currency_amount,
	debt_balance_subposition_usd_amount,
	debt_balance_subposition_document_currency_to_usd_amount,
	debt_balance_subpos_no_revaluation_local_currency_amount,
	debt_balance_subpos_no_revaluation_sec_local_curr_amount,
	debt_balance_subposition_no_revaluation_usd_amount,
	debt_balance_contract_usd_amount,
	debt_balance_contract_document_currency_to_usd_amount,
	debt_balance_contract_no_revaluation_usd_amount,
	paydox_credit_limit_usd_currency_amount,
	invoice_document_code,
	fiscal_year_of_relevant_invoice,
	position_number_of_relevant_invoice,
	final_position_line_item,
	final_fiscal_year,
	final_accounting_document_code,
	exchange_diff_local_currency_amount,
	debt_balance_exchange_diff_local_currency_amount,
	debt_balance_subpos_exch_diff_local_currency_amount,
	exchange_diff_second_local_currency_amount,
	debt_balance_exchange_diff_second_local_currency_amount,
	debt_balance_subpos_exch_diff_second_local_curr_amount,
	counterparty_truncated_code,
	counterparty_search_name,
	responsibility_center_level1_code,
	responsibility_center_level1_name,
	financial_position_code,
	financial_position_name,
	usd_amount,
	realization_invoice_code,
	realization_document_code,
	country_of_end_user_code,
	country_of_end_user_name,
	region_of_end_user_code,
	region_of_end_user_name,
	sales_invoice_code,
	material_shape_code,
	material_shape_name,
	receivable_claim_number,
	receivable_claim_paydox_url,
	dt_receivable_claim,
	reference_operation_type_code,
    reference_object_key_code,
	material_code,
	bank_as_counterparty_code,
	almer_bank_code,
	bank_as_counterparty_name,
	paydox_document_url,
	contract_list,
	contract_list_with_paydox_url,
	external_contract_source_table_name,
	unpaid_payment_request_code,
	purchase_order_code,
	purchase_specification_compound_number,
	dt_edm_counterparty_electonic_signature,
	accounting_document_created_by,
	vat_rate,
	debt_balance_subpos_second_local_currency_amount_reval,
	dt_posting,
	contract_supervisor_user_active_directory_code,
	debt_balance_subpos_exchange_diff_local_currency_amount,
	debt_balance_subpos_exchange_diff_second_local_curr_amount,
	database_code_1c,
	database_name_1c,
	posting_uid_code_1c
)

with paydoxlim as (
	select
		p.dt_report ,
		p.unit_balance_code,
		pcl.credit_limit_counterparty_code,
		sum(pcl.paydox_credit_limit_usd_currency_amount) as paydox_credit_limit_usd_currency_amount
	from
		dm_calc.account_debt_for_working_capital_1c as p
	left join dict_dds.counterparty ct on
		ct.counterparty_mdm_code = p.counterparty_mdm_code 
		and ct.language_code = 'R'
	join dm.paydox_credit_limits as pcl on
		pcl.credit_limit_counterparty_code = ct.counterparty_code
		and (p.dt_report >= pcl.dt_paydox_credit_limit_valid_from
		and p.dt_report <= pcl.dt_paydox_credit_limit_valid_to)
		and pcl.paydox_credit_limit_status_code = '4'
	group by 
		p.dt_report,
		p.unit_balance_code,
		pcl.credit_limit_counterparty_code),
		
second_friday as (
	SELECT month_start, 
	   month_start +
	   (case when EXTRACT(ISODOW FROM month_start::date) <= 5
	   		then (5-EXTRACT(ISODOW FROM month_start::date))
	   else 12-EXTRACT(ISODOW FROM month_start::date) end +7)::int as second_friday,
	   true as is_second_friday
from
		(select
		generate_series('2024-01-01'::date,
	now()::date,
	'1 month'::interval)::date as month_start) as ms)
		
SELECT
	c.dt_report as dt,
	case when sf.second_friday is null then false
		 else true end as is_second_friday,
	c.unit_balance_code,
	c.fiscal_year,
	null as accounting_document_code,
	c.dt_debt,
	coalesce(c.dt_overdue, '2299-12-31') as dt_overdue,
	null as dt_clearing,
	null as contract_number,
	c.counterparty_code,
	c.debit_or_credit_code as debit_or_credit,
	c.account_type_code as account_type,
	c.general_ledger_account_code,
	null as debt_balance_document_currency_amount,
	null as debt_balance_local_currency_amount,
	null as debt_balance_second_local_currency_amount,
	null as debt_balance_with_revaluation_diff_second_currency_amount,
	c.debt_balance_position_usd_amount,
	c.document_currency_code,
	c.local_currency_code,
	null as second_local_currency_code,
	null as accounting_document_type,
	null as accounting_document_type_name,
	null as position_line_item,
	null as reverse_document_code,
	c.reference_document_number,
	null as accounting_document_status_code,
	null as clearing_document_code,
	null as tax_code,
	c.position_line_item_text,
	null as special_general_ledger_indicator,
	c.dt_baseline_due_date_calculation,
	null as assignment_number,
	c.dt_accounting_document,
	null as plant_code,
	null as plant_name,
	c.general_ledger_account_full_name,
	ub.unit_balance_name,
	con.counterparty_full_name,
	c.external_contract_number,
	c.dt_external_contract,
	c.contract_trader_code,
	c.contract_trader_name,
	null as terms_of_payment_code,
	c.terms_of_payment_name,
	null as responsibility_center_code,
	null as responsibility_center_name,
	con.budget_subtype_code,
	c.contract_supervisor_employee_number,
	c.contract_supervisor_name,
	null as purchase_or_sales_group_code,
	null as purchase_or_sales_group_name,
	null as funds_center_code,
	null as funds_center_name,
	null as debt_subposition_number,
	null as debt_subposition_local_currency_amount,
	c.debt_subposition_document_currency_amount,
	null as debt_subposition_second_local_currency_amount,
	null as is_debt_daily_calculated,
	a.country_code,
	con.counterparty_hfm_code,
	c.counterparty_mdm_code,
	con.is_related_party_tco,
	con.is_group_company_affiliated,
	con.is_related_party_rsbo,
	con.is_bankrupt,
	con.is_lawsuit_exist,
	con.is_fns_restriction_list_exist,
	c.document_currency_amount,
	null as local_currency_amount,
	null as second_local_currency_amount,
	con.counterparty_tin_code,
	null as reverse_document_fiscal_year,
	null as reason_for_reversal,
	c.debt_balance_subposition_document_currency_amount,
	c.debt_balance_subposition_local_currency_amount,
	c.debt_balance_subposition_second_local_currency_amount,
	c.debt_balance_subposition_usd_amount,
	c.debt_balance_subposition_document_currency_to_usd_amount,
	c.debt_balance_subpos_no_revaluation_local_currency_amount,
	c.debt_balance_subpos_no_revaluation_sec_local_curr_amount,
	c.debt_balance_subposition_no_revaluation_usd_amount,
	c.debt_balance_contract_usd_amount,
	c.debt_balance_contract_document_currency_to_usd_amount,
	c.debt_balance_contract_no_revaluation_usd_amount,
	paydoxlim.paydox_credit_limit_usd_currency_amount,
	null as invoice_document_code,
	null as fiscal_year_of_relevant_invoice,
	null as position_number_of_relevant_invoice,
	null as final_position_line_item,
	c.final_fiscal_year,
	c.final_accouning_document_code,
	null as exchange_diff_local_currency_amount,
	null as debt_balance_exchange_diff_local_currency_amount,
	null as debt_balance_subpos_exch_diff_local_currency_amount,
	null as exchange_diff_second_local_currency_amount,
	null as debt_balance_exchange_diff_second_local_currency_amount,
	null as debt_balance_subpos_exch_diff_second_local_curr_amount,
	con.counterparty_truncated_code,
	con.counterparty_search_name,
	c.responsibility_center_level1_code,
	rct.responsibility_center_name as responsibility_center_level1_name,
	null as financial_position_code,
	null as financial_position_name,
	c.usd_amount,
	null as realization_invoice_code,
	null as realization_document_code,
	c.country_of_end_user_code,
	ct.country_short_name as country_of_end_user_name,
	c2.market_region1_code as region_of_end_user_code,
	mrt.market_region1_name as region_of_end_user_name,
	null as sales_invoice_code,
	null as material_shape_code,
	c.material_shape_name,
	null as receivable_claim_number,
	c.receivable_claim_paydox_url,
	c.dt_receivable_claim,
	null as reference_operation_type_code,
    null as reference_object_key_code,
	null as material_code,
	null as bank_as_counterparty_code,
	c.bank_receiver_name as almer_bank_code,
	null as bank_as_counterparty_name,
	c.paydox_document_url,
	null as contract_list,
	null as contract_list_with_paydox_url,
	null as external_contract_source_table_name,
	null as unpaid_payment_request_code,
	null as purchase_order_code,
	null as purchase_specification_compound_number,
	null as dt_edm_counterparty_electonic_signature,
	null as accounting_document_created_by,
	null as vat_rate,
	null as debt_balance_subpos_second_local_currency_amount_reval,
	c.dt_posting,
	c.contract_supervisor_user_active_directory_code,
	null as debt_balance_subpos_exchange_diff_local_currency_amount,
	null as debt_balance_subpos_exchange_diff_second_local_curr_amount,
	c.database_code_1c,
	c.database_name_1c,
	c.posting_uid_code_1c
from dm_calc.account_debt_for_working_capital_1c as c
left join second_friday as sf on
	c.dt_report = sf.second_friday
left join dict_dds.counterparty con on 
	c.counterparty_code = con.counterparty_code
left join paydoxlim as paydoxlim on
	c.dt_report = paydoxlim.dt_report
	and c.unit_balance_code = paydoxlim.unit_balance_code
	and c.counterparty_code = paydoxlim.credit_limit_counterparty_code
left join dict_dds.unit_balance ub on
	c.unit_balance_code = ub.unit_balance_code 
	and ub.language_code = 'R'
left join dict_dds.country c2 on
	c2.country_code = c.country_of_end_user_code
left join dict_dds.address a on 
	a.address_code = con.address_code 
	and a.international_display_format_code is null 
	and a.deleted_flag = false
left join dict_dds.responsibility_center_texts rct on
	c.responsibility_center_level1_code = rct.responsibility_center_code 
	and rct.language_code = 'R'
left join dict_dds.country_texts ct on
	c.country_of_end_user_code = ct.country_code
	and ct.language_code = 'R'
left join dict_dds.market_region1_texts mrt on
	c2.market_region1_code = mrt.market_region1_code
	and mrt.language_code = 'R'
where 1=1
	and c.dt_report >= (date_trunc('day', now()) - interval '60 days')::date and c.dt_report <= now();