#!/usr/bin/env python3
"""Helpers for wrapping plain SQL into debug-friendly PL/pgSQL and back."""

from __future__ import annotations

from pathlib import Path

BEGIN_MARKER = "-- >>> SQL_PAYLOAD_BEGIN >>>"
END_MARKER = "-- <<< SQL_PAYLOAD_END <<<"


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def read_source_text(path: str | None) -> str:
    if not path:
        from sys import stdin

        return normalize_newlines(stdin.read())
    return normalize_newlines(Path(path).read_text(encoding="utf-8"))


def write_target_text(path: str | None, text: str) -> None:
    if not path:
        from sys import stdout

        stdout.write(text)
        return
    Path(path).write_text(text, encoding="utf-8")


def wrap_sql_to_plpgsql(sql_text: str, source_name: str) -> str:
    payload = normalize_newlines(sql_text).rstrip("\n")
    payload_lines = payload.split("\n") if payload else []

    lines = [
        "-- generated by wrap_sql_to_plpgsql_debug.py",
        f"-- source: {source_name}",
        "DO $$",
        "DECLARE",
        f"  _source text := {sql_literal(source_name)};",
        "BEGIN",
        "  RAISE NOTICE 'wrap_sql_to_plpgsql_debug: start %', _source;",
        BEGIN_MARKER,
    ]
    lines.extend(payload_lines)
    lines.extend(
        [
            END_MARKER,
            "  RAISE NOTICE 'wrap_sql_to_plpgsql_debug: done %', _source;",
            "END",
            "$$ LANGUAGE plpgsql;",
            "",
        ]
    )
    return "\n".join(lines)


def unwrap_plpgsql_to_sql(plpgsql_text: str) -> str:
    lines = normalize_newlines(plpgsql_text).split("\n")
    try:
        begin_index = lines.index(BEGIN_MARKER)
        end_index = lines.index(END_MARKER)
    except ValueError as exc:
        raise ValueError(
            "Payload markers were not found. This unwrap utility expects output generated by wrap_sql_to_plpgsql_debug.py."
        ) from exc

    if end_index < begin_index:
        raise ValueError("Payload markers are in the wrong order.")

    payload = "\n".join(lines[begin_index + 1 : end_index]).rstrip("\n")
    return payload + ("\n" if payload else "")


def default_source_name(path: str | None) -> str:
    if not path:
        return "stdin.sql"
    return Path(path).name
