insert into ods.ral_map_alverse_sales_life_cycle (
    customer_code,
    contract_code,
    delivery_code,
    delivery_position_code,
    created_by,
    document_type_name,
    document_status_name,
    unit_balance_code,
    unit_balance_currency_code,
    plant_producer_unit_balance_code,
    seller_unit_balance_code,
    customer_name,
    contract_producer_code,
    contract_producer_name,
    contract_trader_code,
    contract_trader_name,
    contract_external_number,
    contract_currency_code,
    contract_incoterms_code,
    vat_rate,
    agent_contract_code,
    dt_posting,
    dt_currency_exchange_rate_for_payment,
    usd_exchange_rate_for_payment,
    payment_usd_amount,
    gnr_plant_short_eng_name,
    gnr_net_weight,
    gnr_weight_uom_code,
    gnr_revenue_document_currency_amount,
    dt_gnr_currency_translation_to_usd,
    gnr_revenue_currency_translation_to_usd_rate,
    gnr_revenue_local_currency_amount,
    gnr_local_currency_code,
    gnr_consignee_code,
    gnr_consignee_name,
    gnr_material_code,
    gnr_material_specification_name,
    gnr_material_aggr_name,
    clearing_status_code,
    gnr_contract_lme_qp_amount,
    gnr_contract_premium_amount,
    gnr_contract_premium_total_amount,
    is_edm_applicable_code,
    sr_trader_code,
    sr_sales_request_code,
    sr_plant_code,
    sr_plant_short_rus_name,
    sr_transport_type_code,
    sr_ingot_per_unit_net_weight,
    sr_transportation_service_payed_by_code,
    sr_consignee_code,
    sr_consignee_name,
    dt_sr_quota_yyyymm,
    sr_created_by,
    sr_terms_of_payment_code,
    sr_terms_of_payment_name,
    dt_sr_payment,
    sr_remote_warehouse_shipment_forwarder_code,
    dt_si_shipment_instruction,
    si_incoterms_code,
    si_transportation_service_payed_by_name,
    od_unit_balance_owner_code,
    od_plant_owner_code,
    od_ownership_transfer_code,
    od_agency_contract_code,
    dt_od_outbound_delivery_created,
    dt_od_shipment_from_warehouse,
    dt_od_shipment_from_plant,
    dt_od_shipment_from_plant_plus5_days,
    dt_od_ownership_transfer,
    od_seller_code,
    od_transport_type_code,
    od_transport_vehicle_code,
    od_transport_capacity,
    od_transport_bill_code,
    od_material_attribute_text,
    dt_od_price,
    od_price_vat_excluded_amount,
    od_price_currency_code,
    od_transaction_currency_code,
    od_currency_translation_rate,
    od_weight_net_with_wirerod,
    od_initial_delivery_code,
    od_initial_delivery_position_code,
    od_inbound_delivery_code,
    od_batch_code,
    od_outbound_delivery_status_code,
    odp_entry_system_code,
    odp_local_currency_code,
    odp_second_local_currency_code,
    pr_payment_return_document_code,
    dt_pr_payment_return_document_yyyy,
    pr_document_reverse_code,
    dt_ri_realization_invoice,
    dt_ri_posting,
    ri_realization_invoice_code,
    ri_realization_invoice_agent_reverse_code,
    dt_ri_currency_translation_to_usd,
    ri_realization_invoice_external_number,
    ri_vat_code,
    ri_realization_invoice_comment_text,
    ai_unit_balance_code,
    dt_ai_agent_invoice,
    ai_agent_invoice_code,
    ai_agent_invoice_reverse_code,
    ai_contract_code,
    dt_ai_currency_translation_to_usd,
    ai_currency_translation_to_usd_rate,
    ai_agent_invoice_external_number,
    oi_accounting_document_code,
    oi_fiscal_year,
    oi_owner_invoice_code,
    oi_owner_invoice_position_code,
    dt_oi_currency_translation_to_usd,
    oi_owner_invoice_external_number,
    dt_oi_accounting_document,
    dt_oi_posting,
    di_deferred_invoice_code,
    di_accounting_document_code,
    di_accounting_document_reverse_code,
    di_deferred_invoice_external_number,
    dt_oi_owner_invoice_created,
    oi_currency_translation_to_usd_rate,
    oi_vat_included_rub_amount,
    oi_vat_included_usd_amount,
    edm_code,
    edm_status_code,
    dt_edm_status_last_updated
)
select 
    tech_etl.util_text_to_null_validation(bi."KUNNRKEY") as customer_code,
    tech_etl.util_text_to_null_validation(bi."VERTNKEY") as contract_code,
    tech_etl.util_text_to_null_validation(bi."FO_VBELNKEY") as delivery_code,
    tech_etl.util_text_to_null_validation(bi."FO_POSNRKEY") as delivery_position_code,
    tech_etl.util_text_to_null_validation(bi."USNAM") as created_by,
    tech_etl.util_text_to_null_validation(bi."D_NAME") as document_type_name,
    tech_etl.util_text_to_null_validation(bi."D_STATUS") as document_status_name,
    tech_etl.util_text_to_null_validation(bi."BUKRS") as unit_balance_code,
    tech_etl.util_text_to_null_validation(bi."BUKRS_WAERS") as unit_balance_currency_code,
    tech_etl.util_text_to_null_validation(bi."BUKRS_PR") as plant_producer_unit_balance_code,
    tech_etl.util_text_to_null_validation(bi."BUKRS_LIFNR") as seller_unit_balance_code,
    tech_etl.util_text_to_null_validation(bi."NAME_KUNNR") as customer_name,
    tech_etl.util_text_to_null_validation(bi."VERTN_PR") as contract_producer_code,
    tech_etl.util_text_to_null_validation(bi."VERTN_PR_NAME") as contract_producer_name,
    tech_etl.util_text_to_null_validation(bi."TRADER") as contract_trader_code,
    tech_etl.util_text_to_null_validation(bi."TRADER_NAME") as contract_trader_name,
    tech_etl.util_text_to_null_validation(bi."NAME_VERTN") as contract_external_number,
    tech_etl.util_text_to_null_validation(bi."WAERS") as contract_currency_code,
    tech_etl.util_text_to_null_validation(bi."INCO1") as contract_incoterms_code,
    tech_etl.util_text_to_null_validation(bi."PROC_NDS") as vat_rate,
    tech_etl.util_text_to_null_validation(bi."VERTN_S") as agent_contract_code,
    tech_etl.util_text_to_date_validation(bi."BUDAT_BY") as dt_posting,
    tech_etl.util_text_to_date_validation(bi."DATE_RATE") as dt_currency_exchange_rate_for_payment,
    bi."USD_RATE" as usd_exchange_rate_for_payment,
    bi."SUMM_PAY" as payment_usd_amount,
    tech_etl.util_text_to_null_validation(bi."ZAVOD") as gnr_plant_short_eng_name,
    bi."LFIMG" as gnr_net_weight,
    tech_etl.util_text_to_null_validation(bi."VRKME") as gnr_weight_uom_code,
    bi."O_WRBTR" as gnr_revenue_document_currency_amount,
    tech_etl.util_text_to_date_validation(bi."WWERT") as dt_gnr_currency_translation_to_usd,
    bi."KURSF" as gnr_revenue_currency_translation_to_usd_rate,
    bi."O_DMBTR" as gnr_revenue_local_currency_amount,
    tech_etl.util_text_to_null_validation(bi."HWAER") as gnr_local_currency_code,
    tech_etl.util_text_to_null_validation(bi."GRUZPOL") as gnr_consignee_code,
    tech_etl.util_text_to_null_validation(bi."GRUZPOL_NAME") as gnr_consignee_name,
    tech_etl.util_text_to_null_validation(bi."MATNR") as gnr_material_code,
    tech_etl.util_text_to_null_validation(bi."NSPECIF") as gnr_material_specification_name,
    tech_etl.util_text_to_null_validation(bi."PIMARY") as gnr_material_aggr_name,
    tech_etl.util_text_to_null_validation(bi."VR_STATUS") as clearing_status_code,
    bi."LME" as gnr_contract_lme_qp_amount,
    bi."Z005" as gnr_contract_premium_amount,
    bi."PR_CONTRACTPREMUSD" as gnr_contract_premium_total_amount,
    tech_etl.util_text_to_null_validation(bi."ZEDO") as is_edm_applicable_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_TRADER") as sr_trader_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_ZAKAZ_KL") as sr_sales_request_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_WERKS") as sr_plant_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_WERKS_NAME") as sr_plant_short_rus_name,
    tech_etl.util_text_to_null_validation(bi2."ZP_TRANSPORT") as sr_transport_type_code,
    tech_etl.util_text_to_null_validation(trim(bi2."ZP_WEIGHT_BASE")) as sr_ingot_per_unit_net_weight, -- trim
    tech_etl.util_text_to_null_validation(bi2."ZP_ZPEREV") as sr_transportation_service_payed_by_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_GRUZPOL") as sr_consignee_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_GRUZPOL_NAME") as sr_consignee_name,
    tech_etl.util_text_to_null_validation(bi2."ZP_QUOTA") as dt_sr_quota_yyyymm,
    tech_etl.util_text_to_null_validation(bi2."ZP_ERNAM") as sr_created_by,
    tech_etl.util_text_to_null_validation(bi2."ZP_ZTERM") as sr_terms_of_payment_code,
    tech_etl.util_text_to_null_validation(bi2."ZP_ZTERM_NAME") as sr_terms_of_payment_name,
    tech_etl.util_text_to_date_validation(bi2."ZP_ZTERM_DATE") as dt_sr_payment,
    tech_etl.util_text_to_null_validation(bi2."ZP_GRUZOTP") as sr_remote_warehouse_shipment_forwarder_code,
    tech_etl.util_text_to_date_validation(bi2."R_AUDAT") as dt_si_shipment_instruction,
    tech_etl.util_text_to_null_validation(bi2."R_INCO1") as si_incoterms_code,
    tech_etl.util_text_to_null_validation(bi2."R_ZZPEREV") as si_transportation_service_payed_by_name,
    tech_etl.util_text_to_null_validation(bi2."FO_BUKRS") as od_unit_balance_owner_code,
    tech_etl.util_text_to_null_validation(bi2."FO_WERKS") as od_plant_owner_code,
    tech_etl.util_text_to_null_validation(bi2."FO_KVGR2") as od_ownership_transfer_code,
    tech_etl.util_text_to_null_validation(bi2."FO_VERTN_A") as od_agency_contract_code,
    tech_etl.util_text_to_date_validation(bi2."FO_ERDAT") as dt_od_outbound_delivery_created,
    tech_etl.util_text_to_date_validation(bi2."FO_KODAT") as dt_od_shipment_from_warehouse,
    tech_etl.util_text_to_date_validation(bi2."FO_LDDAT") as dt_od_shipment_from_plant,
    tech_etl.util_text_to_date_validation(bi2."FO_LDDAT_5") as dt_od_shipment_from_plant_plus5_days,
    tech_etl.util_text_to_date_validation(bi2."FO_WADAT_IST") as dt_od_ownership_transfer,
    tech_etl.util_text_to_null_validation(bi2."FO_LIFNR") as od_seller_code,
    tech_etl.util_text_to_null_validation(bi2."FO_WAGTYPE") as od_transport_type_code,
    tech_etl.util_text_to_null_validation(bi2."FO_VAGON") as od_transport_vehicle_code,
    bi2."FO_GRUZ" as od_transport_capacity,
    tech_etl.util_text_to_null_validation(bi2."FO_NAKLADN") as od_transport_bill_code,
    tech_etl.util_text_to_null_validation(bi2."FO_MATNR_MFR") as od_material_attribute_text,
    tech_etl.util_text_to_date_validation(bi2."FO_PRSDT") as dt_od_price,
    bi2."FO_KBETR" as od_price_vat_excluded_amount,
    tech_etl.util_text_to_null_validation(bi2."FO_KOEI1") as od_price_currency_code,
    tech_etl.util_text_to_null_validation(bi2."FO_WAERS") as od_transaction_currency_code,
    bi2."FO_KURSF" as od_currency_translation_rate,
    bi2."FO_NK" as od_weight_net_with_wirerod,
    tech_etl.util_text_to_null_validation(bi2."FO_VBELN_ZV") as od_initial_delivery_code,
    tech_etl.util_text_to_null_validation(bi2."FO_POSNR_ZV") as od_initial_delivery_position_code,
    tech_etl.util_text_to_null_validation(bi2."FO_VBELN_IN") as od_inbound_delivery_code,
    tech_etl.util_text_to_null_validation(bi2."FO_CHARG") as od_batch_code,
    tech_etl.util_text_to_null_validation(bi2."FO_WBSTA") as od_outbound_delivery_status_code,
    tech_etl.util_text_to_null_validation(bi2."PP_FO_ID") as odp_entry_system_code,
    tech_etl.util_text_to_null_validation(bi2."PP_FO_HWAER") as odp_local_currency_code,
    tech_etl.util_text_to_null_validation(bi2."PP_FO_HWAE2") as odp_second_local_currency_code,
    tech_etl.util_text_to_null_validation(bi2."V_BELNR") as pr_payment_return_document_code,
    tech_etl.util_text_to_null_validation(bi2."V_GJAHR") as dt_pr_payment_return_document_yyyy,
    tech_etl.util_text_to_null_validation(bi2."V_BELNR_S") as pr_document_reverse_code,
    tech_etl.util_text_to_date_validation(bi3."FR_BLDAT") as dt_ri_realization_invoice,
    tech_etl.util_text_to_date_validation(bi3."FR_BUDAT") as dt_ri_posting,
    tech_etl.util_text_to_null_validation(bi3."FR_BELNR") as ri_realization_invoice_code,
    tech_etl.util_text_to_null_validation(bi3."FR_BELNR_S") as ri_realization_invoice_agent_reverse_code,
    tech_etl.util_text_to_date_validation(bi3."FR_WWERT") as dt_ri_currency_translation_to_usd,
    tech_etl.util_text_to_null_validation(bi3."FR_XBLNR") as ri_realization_invoice_external_number,
    tech_etl.util_text_to_null_validation(bi3."FR_MWSKZ") as ri_vat_code,
    tech_etl.util_text_to_null_validation(bi3."FR_SGTXT") as ri_realization_invoice_comment_text,
    tech_etl.util_text_to_null_validation(bi3."FA_BUKRS") as ai_unit_balance_code,
    tech_etl.util_text_to_date_validation(bi3."FA_BLDAT") as dt_ai_agent_invoice,
    tech_etl.util_text_to_null_validation(bi3."FA_BELNR") as ai_agent_invoice_code,
    tech_etl.util_text_to_null_validation(bi3."FA_BELNR_S") as ai_agent_invoice_reverse_code,
    tech_etl.util_text_to_null_validation(bi3."FA_VERTN") as ai_contract_code,
    tech_etl.util_text_to_date_validation(bi3."FA_WWERT") as dt_ai_currency_translation_to_usd,
    bi3."FA_KURSF" as ai_currency_translation_to_usd_rate,
    tech_etl.util_text_to_null_validation(bi3."FA_XBLNR") as ai_agent_invoice_external_number,
    tech_etl.util_text_to_null_validation(bi3."FS_BELNR") as oi_accounting_document_code,
    tech_etl.util_text_to_null_validation(bi3."FS_GJAHR") as oi_fiscal_year,
    tech_etl.util_text_to_null_validation(bi3."FS_VBELN") as oi_owner_invoice_code,
    tech_etl.util_text_to_null_validation(bi3."FS_POSNR") as oi_owner_invoice_position_code,
    tech_etl.util_text_to_date_validation(bi3."FS_WWERT") as dt_oi_currency_translation_to_usd,
    tech_etl.util_text_to_null_validation(bi3."FS_XBLNR") as oi_owner_invoice_external_number,
    tech_etl.util_text_to_date_validation(bi3."FS_BLDAT") as dt_oi_accounting_document,
    tech_etl.util_text_to_date_validation(bi3."FS_BUDAT") as dt_oi_posting,
    tech_etl.util_text_to_null_validation(bi3."FS2_VBELN") as di_deferred_invoice_code,
    tech_etl.util_text_to_null_validation(bi3."FS2_BELNR") as di_accounting_document_code,
    tech_etl.util_text_to_null_validation(bi3."FS2_BELNR_S") as di_accounting_document_reverse_code,
    tech_etl.util_text_to_null_validation(bi3."FS2_XBLNR") as di_deferred_invoice_external_number,
    tech_etl.util_text_to_date_validation(bi3."FS_CPUDT") as dt_oi_owner_invoice_created,
    bi3."FS_KURSF2" as oi_currency_translation_to_usd_rate,
    bi3."FS_KWERT" as oi_vat_included_rub_amount,
    bi3."FS_KWERT_USD" as oi_vat_included_usd_amount,
    tech_etl.util_text_to_null_validation(bi3."FE_N") as edm_code,
    tech_etl.util_text_to_null_validation(bi3."FE_STATUSP") as edm_status_code,
    tech_etl.util_text_to_date_validation(bi3."FE_DATE_ST") as dt_edm_status_last_updated
from stg."ZFI3436M_BI" bi
left join stg."ZFI3436M_BI2" bi2 
    on bi."KUNNRKEY" = bi2."KUNNRKEY" 
    and bi."VERTNKEY" = bi2."VERTNKEY" 
    and bi."FO_VBELNKEY" = bi2."FO_VBELNKEY" 
    and bi."FO_POSNRKEY" = bi2."FO_POSNRKEY"
left join stg."ZFI3436M_BI3" bi3 
    on bi."KUNNRKEY" = bi3."KUNNRKEY" 
    and bi."VERTNKEY" = bi3."VERTNKEY" 
    and bi."FO_VBELNKEY" = bi3."FO_VBELNKEY" 
    and bi."FO_POSNRKEY" = bi3."FO_POSNRKEY";
    