insert into ods.account_debt_for_working_capital_1c (
	sender,
	receiver,
	create_date_time,
	dt_report,
	database_code_1c,
	database_name_1c,
	unit_balance_mdm_code_1c,
	posting_uid_code_1c,
	invoice_registration_number,
	counterparty_role_name,
	debit_or_credit_name,
	accounting_document_descriprion_text,
	document_1c_code,
	responsibility_center_hfm_code,
	region_of_end_user_code,
	country_of_end_user_code,
	counterparty_mdm_code,
	counterparty_annual_turnover_amount,
	finish_goods_group_name,
	contract_number,
	paydox_document_url,
	contract_type_name,
	contract_amount,
	contract_currency_code,
	dt_contract_start,
	dt_contract_end,
	terms_of_payment_name,
	dt_overdue,
	debt_coverage_type_name,
	coverage_amount,
	coverage_currency_code,
	dt_debt,
	document_currency_code,
	debt_balance_document_currency_amount,
	debt_balance_rub_currency_amount,
	debt_balance_usd_currency_amount,
	debt_overdue_document_currency_amount,
	debt_overdue_rub_currency_amount,
	debt_overdue_usd_currency_amount,
	bank_receiver_name,
	receivable_claim_paydox_url,
	dt_receivable_claim,
	dt_claim_send_to_law_court,
	contract_supervisor_name,
	contract_supervisor_ad_login_code,
	general_ledger_account_code,
	general_ledger_account_name,
	dt_contract_registration,
	document_currency_amount,
	contract_supervisor_employee_1c_number,
	contract_supervisor_employee_sap_number,
	sales_market_code,
	sales_market_name,
	bad_debt_provision_amount,
	bad_debt_provision_currency_code,
	credit_limit_rub_currency_amount,
	dt_credit_limit_valid_to,
	paydox_credit_limit_url,
	insured_amount,
	insurance_currency_code,
	dt_insurance_valid_to,
	insurance_company_mdm_code,
	bank_guarantee_amount,
	bank_guarantee_currency_code,
	dt_bank_guarantee_valid_to,
	bank_guarantee_mdm_code,
	third_party_guarantee_amount,
	third_party_guarantee_currency_code,
	dt_third_party_guarantee_valid_to,
	third_party_guarantee_mdm_code
)
with cte as (
SELECT distinct
	c.sender,
	c.receiver,
	c.create_date_time,
	case when c.dt_report < '19000101' then '19000101'
		 when c.dt_report > '22991231' then '22991231'
		 else c.dt_report end as dt_report,
	c.database_code_1c,
	c.database_name_1c,
	c.unit_balance_mdm_code_1c,
	c.posting_uid_code_1c,
	c.invoice_registration_number,
	c.counterparty_role_name,
	c.debit_or_credit_name,
	c.accounting_document_descriprion_text,
	c.document_1c_code,
	c.responsibility_center_hfm_code,
	c.region_of_end_user_code,
	c.country_of_end_user_code,
	c.counterparty_mdm_code,
	c.counterparty_annual_turnover_amount,
	c.finish_goods_group_name,
	c.contract_number,
	case when c.paydox_document_url like '%https://paydox%' or c.paydox_document_url like '%http://paydox%'
		then c.paydox_document_url
		else null end as paydox_document_url,
	c.contract_type_name,
	c.contract_amount,
	c.contract_currency_code,
	case when c.dt_contract_start < '19000101' then '19000101'
		 when c.dt_contract_start > '22991231' then '22991231'
		 else c.dt_contract_start end as dt_contract_start,
	case when c.dt_contract_end < '19000101' then '19000101'
		 when c.dt_contract_end > '22991231' then '22991231'
		 else c.dt_contract_end end as dt_contract_end,
	c.terms_of_payment_name,
	case when c.dt_overdue < '19000101' then '19000101'
		 when c.dt_overdue > '22991231' then '22991231'
		 else c.dt_overdue end as dt_overdue,
	c.debt_coverage_type_name,
	c.coverage_amount,
	c.coverage_currency_code,
	case when c.dt_debt < '19000101' then '19000101'
		 when c.dt_debt > '22991231' then '22991231'
		 else c.dt_debt end as dt_debt,
	c.document_currency_code,
	c.debt_balance_document_currency_amount,
	c.debt_balance_rub_currency_amount,
	c.debt_balance_usd_currency_amount,
	c.debt_overdue_document_currency_amount,
	c.debt_overdue_rub_currency_amount,
	c.debt_overdue_usd_currency_amount,
	c.bank_receiver_name,
	c.receivable_claim_paydox_url,
	case when c.dt_receivable_claim < '19000101' then '19000101'
		 when c.dt_receivable_claim > '22991231' then '22991231'
		 else c.dt_receivable_claim end as dt_receivable_claim,
	case when c.dt_claim_send_to_law_court < '19000101' then '19000101'
		 when c.dt_claim_send_to_law_court > '22991231' then '22991231'
		 else c.dt_claim_send_to_law_court end as dt_claim_send_to_law_court,
	c.contract_supervisor_name,
	c.contract_supervisor_ad_login_code,
	c.general_ledger_account_code,
	c.general_ledger_account_name,
	case when c.dt_contract_registration < '19000101' then '19000101'
		 when c.dt_contract_registration > '22991231' then '22991231'
		 else c.dt_contract_registration end as dt_contract_registration,
	c.document_currency_amount,
	c.contract_supervisor_employee_1c_number,
	c.contract_supervisor_employee_sap_number,
	c.sales_market_code,
	c.sales_market_name,
	c.bad_debt_provision_amount,
	c.bad_debt_provision_currency_code,
	c.credit_limit_rub_currency_amount,
	case when c.dt_credit_limit_valid_to < '19000101' then '19000101'
		 when c.dt_credit_limit_valid_to > '22991231' then '22991231'
		 else c.dt_credit_limit_valid_to end as dt_credit_limit_valid_to,
	c.paydox_credit_limit_url,
	c.insured_amount,
	c.insurance_currency_code,
	case when c.dt_insurance_valid_to < '19000101' then '19000101'
		 when c.dt_insurance_valid_to > '22991231' then '22991231'
		 else c.dt_insurance_valid_to end as dt_insurance_valid_to,
	c.insurance_company_mdm_code,
	c.bank_guarantee_amount,
	c.bank_guarantee_currency_code,
	case when c.dt_bank_guarantee_valid_to < '19000101' then '19000101'
		 when c.dt_bank_guarantee_valid_to > '22991231' then '22991231'
		 else c.dt_bank_guarantee_valid_to end as dt_bank_guarantee_valid_to,
	c.bank_guarantee_mdm_code,
	c.third_party_guarantee_amount,
	c.third_party_guarantee_currency_code,
	case when c.dt_third_party_guarantee_valid_to < '19000101' then '19000101'
		 when c.dt_third_party_guarantee_valid_to > '22991231' then '22991231'
		 else c.dt_third_party_guarantee_valid_to end as dt_third_party_guarantee_valid_to,
	c.third_party_guarantee_mdm_code,
	c.dt_insert,
	dense_rank() over (partition by c.unit_balance_mdm_code_1c, c.dt_report order by c.dt_insert desc) as rn
FROM stg.s1c_debt_for_working_capital as c),

cte2 as (
select
	c2.sender,
	c2.receiver,
	c2.create_date_time,
	c2.dt_report,
	c2.database_code_1c,
	c2.database_name_1c,
	c2.unit_balance_mdm_code_1c,
	c2.posting_uid_code_1c,
	c2.invoice_registration_number,
	c2.counterparty_role_name,
	c2.debit_or_credit_name,
	c2.accounting_document_descriprion_text,
	c2.document_1c_code,
	c2.responsibility_center_hfm_code,
	c2.region_of_end_user_code,
	c2.country_of_end_user_code,
	c2.counterparty_mdm_code,
	c2.counterparty_annual_turnover_amount,
	c2.finish_goods_group_name,
	c2.contract_number,
	c2.paydox_document_url,
	c2.contract_type_name,
	c2.contract_amount,
	c2.contract_currency_code,
	c2.dt_contract_start,
	c2.dt_contract_end,
	c2.terms_of_payment_name,
	c2.dt_overdue,
	c2.debt_coverage_type_name,
	c2.coverage_amount,
	c2.coverage_currency_code,
	c2.dt_debt,
	c2.document_currency_code,
	c2.debt_balance_document_currency_amount,
	c2.debt_balance_rub_currency_amount,
	c2.debt_balance_usd_currency_amount,
	c2.debt_overdue_document_currency_amount,
	c2.debt_overdue_rub_currency_amount,
	c2.debt_overdue_usd_currency_amount,
	c2.bank_receiver_name,
	c2.receivable_claim_paydox_url,
	c2.dt_receivable_claim,
	c2.dt_claim_send_to_law_court,
	c2.contract_supervisor_name,
	c2.contract_supervisor_ad_login_code,
	c2.general_ledger_account_code,
	c2.general_ledger_account_name,
	c2.dt_contract_registration,
	c2.document_currency_amount,
	c2.contract_supervisor_employee_1c_number,
	c2.contract_supervisor_employee_sap_number,
	c2.sales_market_code,
	c2.sales_market_name,
	c2.bad_debt_provision_amount,
	c2.bad_debt_provision_currency_code,
	c2.credit_limit_rub_currency_amount,
	c2.dt_credit_limit_valid_to,
	c2.paydox_credit_limit_url,
	c2.insured_amount,
	c2.insurance_currency_code,
	c2.dt_insurance_valid_to,
	c2.insurance_company_mdm_code,
	c2.bank_guarantee_amount,
	c2.bank_guarantee_currency_code,
	c2.dt_bank_guarantee_valid_to,
	c2.bank_guarantee_mdm_code,
	c2.third_party_guarantee_amount,
	c2.third_party_guarantee_currency_code,
	c2.dt_third_party_guarantee_valid_to,
	c2.third_party_guarantee_mdm_code,
	row_number() over (partition by c2.unit_balance_mdm_code_1c, c2.posting_uid_code_1c, c2.dt_report order by c2.create_date_time desc) as rn
from cte as c2
where 1=1
	and c2.rn=1
	and c2.dt_report <> '1900-01-01'
)

select
	c.sender,
	c.receiver,
	c.create_date_time,
	c.dt_report,
	c.database_code_1c,
	c.database_name_1c,
	c.unit_balance_mdm_code_1c,
	c.posting_uid_code_1c,
	c.invoice_registration_number,
	c.counterparty_role_name,
	c.debit_or_credit_name,
	c.accounting_document_descriprion_text,
	c.document_1c_code,
	c.responsibility_center_hfm_code,
	c.region_of_end_user_code,
	c.country_of_end_user_code,
	c.counterparty_mdm_code,
	c.counterparty_annual_turnover_amount,
	c.finish_goods_group_name,
	c.contract_number,
	c.paydox_document_url,
	c.contract_type_name,
	c.contract_amount,
	c.contract_currency_code,
	c.dt_contract_start,
	c.dt_contract_end,
	c.terms_of_payment_name,
	c.dt_overdue,
	c.debt_coverage_type_name,
	c.coverage_amount,
	c.coverage_currency_code,
	c.dt_debt,
	c.document_currency_code,
	c.debt_balance_document_currency_amount,
	c.debt_balance_rub_currency_amount,
	c.debt_balance_usd_currency_amount,
	c.debt_overdue_document_currency_amount,
	c.debt_overdue_rub_currency_amount,
	c.debt_overdue_usd_currency_amount,
	c.bank_receiver_name,
	c.receivable_claim_paydox_url,
	c.dt_receivable_claim,
	c.dt_claim_send_to_law_court,
	c.contract_supervisor_name,
	c.contract_supervisor_ad_login_code,
	c.general_ledger_account_code,
	c.general_ledger_account_name,
	c.dt_contract_registration,
	c.document_currency_amount,
	c.contract_supervisor_employee_1c_number,
	c.contract_supervisor_employee_sap_number,
	c.sales_market_code,
	c.sales_market_name,
	c.bad_debt_provision_amount,
	c.bad_debt_provision_currency_code,
	c.credit_limit_rub_currency_amount,
	c.dt_credit_limit_valid_to,
	c.paydox_credit_limit_url,
	c.insured_amount,
	c.insurance_currency_code,
	c.dt_insurance_valid_to,
	c.insurance_company_mdm_code,
	c.bank_guarantee_amount,
	c.bank_guarantee_currency_code,
	c.dt_bank_guarantee_valid_to,
	c.bank_guarantee_mdm_code,
	c.third_party_guarantee_amount,
	c.third_party_guarantee_currency_code,
	c.dt_third_party_guarantee_valid_to,
	c.third_party_guarantee_mdm_code
from cte2 as c
where 1=1
	and c.rn=1;