insert into ods.easu_lp_v_frozen_product(
	dat,
	id_restfrozenrow,
	keysap,
	shape,
	std,
	mark,
	pack,
	razmer,
	monthregistry,
	ordercc,
	customer,
	nettofrozen,
	namefrozentype,
	id_frozentype,
	noteplant,
	notead,
	notedsb,
	notedtil,
	netto_ad,
	netto_dsb,
	netto_drvr,
	netto_dd,
	netto_dtil,
	id_place,
	sgp,
	smelter,
	namefrozenresponsible
)
select 
	"DAT" as dat,
	tech_etl.util_text_to_null_validation("ID_RESTFROZENROW") as id_restfrozenrow,
	tech_etl.util_text_to_null_validation("KEYSAP") as keysap,
	tech_etl.util_text_to_null_validation("SHAPE") as shape,
	tech_etl.util_text_to_null_validation("STD") as std,
	tech_etl.util_text_to_null_validation("MARK") as mark,
	tech_etl.util_text_to_null_validation("PACK") as pack,
	tech_etl.util_text_to_null_validation("RAZMER") as razmer,
	"MONTHREGISTRY" as monthregistry,
	tech_etl.util_text_to_null_validation("ORDERCC") as ordercc,
	tech_etl.util_text_to_null_validation("CUSTOMER") as customer,
	"NETTOFROZEN" as nettofrozen,
	tech_etl.util_text_to_null_validation("NAMEFROZENTYPE") as namefrozentype,
	"ID_FROZENTYPE" as id_frozentype,
	tech_etl.util_text_to_null_validation("NOTEPLANT") as noteplant,
	tech_etl.util_text_to_null_validation("NOTEAD") as notead,
	tech_etl.util_text_to_null_validation("NOTEDSB") as notedsb,
	tech_etl.util_text_to_null_validation("NOTEDTIL") as notedtil,
	"NETTO_AD" as netto_ad,
	"NETTO_DSB" as netto_dsb,
	"NETTO_DRVR" as netto_drvr,
	"NETTO_DD" as netto_dd,
	"NETTO_DTIL" as netto_dtil,
	"ID_PLACE" as id_place,
	tech_etl.util_text_to_null_validation("SGP") as sgp,
	tech_etl.util_text_to_null_validation("SMELTER") as smelter,
	tech_etl.util_text_to_null_validation("NAMEFROZENRESPONSIBLE") as namefrozenresponsible
from 
	stg."EASU_LP_V_FROZEN_PRODUCT"
where
	"DELETED_FLAG" = false;