insert into ods.asuzdc_provision_conts(
werks,
home_name,
pr_tk, 
kpr_owner,
own,
foot,
id_group, 
fact_cnt_send,
plant_fact_cnt_send,
fact_cnt_loc,
cnt_cont_full,
cnt_cont_empt,
cnt_cont_break,
ove_cnt_cont_full,
ove_cnt_cont_empt,
ove_cnt_car_empt,
ove_cnt_car_full,
cnt_cont_disl,
cnt_car_disl,
skpp,
skpp_ready,
plan_cnt_all,
plan_cnt_ready,
cnt_car_full,
cnt_car_empt,
cnt_car_break)
select 
tech_etl.util_text_to_null_validation ("WERKS") as werks,
tech_etl.util_text_to_null_validation ("HOME_NAME") as home_name,
tech_etl.util_text_to_null_validation ("PR_TK"::varchar) as pr_t,
tech_etl.util_text_to_null_validation ("KPR_OWNER"::varchar) as kpr_owner,
tech_etl.util_text_to_null_validation ("OWN") as own,
tech_etl.util_text_to_null_validation ("FOOT")as foot,
tech_etl.util_text_to_null_validation ("ID_GROUP"::varchar) as id_group, 
"FACT_CNT_SEND" as fact_cnt_send,
"PLANT_FACT_CNT_SEND" as plant_fact_cnt_send,
"FACT_CNT_LOC" as fact_cnt_loc,
"CNT_CONT_FULL" as cnt_cont_full,
"CNT_CONT_EMPT" as cnt_cont_empt,
"CNT_CONT_BREAK" as cnt_cont_break,
"OVE_CNT_CONT_FULL" as ove_cnt_cont_full,
"OVE_CNT_CONT_EMPT" as ove_cnt_cont_empt,
"OVE_CNT_CAR_EMPT" as ove_cnt_car_empt,
"OVE_CNT_CAR_FULL" as ove_cnt_car_full,
"CNT_CONT_DISL" as cnt_cont_disl,
"CNT_CAR_DISL" as cnt_car_disl,
"SKPP" as skpp,
"SKPP_READY" as skpp_ready,
"PLAN_CNT_ALL" as plan_cnt_all,
"PLAN_CNT_READY" as plan_cnt_ready,
"CNT_CAR_FULL" as cnt_car_full,
"CNT_CAR_EMPT" as cnt_car_empt,
"CNT_CAR_BREAK" as cnt_car_break
from stg.asuzdc_provision_conts;