INSERT INTO dm.sales_alverse_mlc (
	batch,															-- SD.000004 "Партия" 
	sales_order_in_shipment,										-- SD.000005 "Заказ ЦК в отгрузке" 
	plant_producer_code,											-- SD.000006 "Завод производитель (код)" 
	plant_producer_name,											-- SD.000007 "Завод" 
	port_of_loading_name,											-- SD.000009 "Направление" 
	dt_shipment,													-- SD.000010 "Дата отгрузки" 
	dt_arrival_by_railway,											-- SD.000011 "Дата прибытия по ЖД" 
	dt_forwarder,													-- SD.000012 "Дата экспедитора" 
	material_aggr_name,												-- SD.000016 "Материал" 
	material_group_code,											-- SD.000017 "Группа материалов" 
	forwarder_name,													-- SD.000021 "Экспедитор" 
	dt_warehouse,													-- SD.000024 "Дата склада" 
	transport_railcar_type_name,									-- SD.000029 "Тип вагона" 
	weight_gross,													-- SD.000031 "Вес брутто" 
	weight_net,														-- SD.000032 "Вес нетто" 
	weight_net_with_wirerod,										-- SD.000033 "Вес Н&K" 
	customer_name,													-- SD.000037 "Покупатель" 
	contract_name, 													-- SD.000038 "Контракт" 
	dt_bill_of_lading,												-- SD.000042 "Дата коносамента" 
	dt_bill_of_lading_in_foreign_port,								-- SD.000049 "Дата коносамента в ин.порту" 
	dt_sailed_loading_port,											-- SD.000058 "Дата отплытия из порта погрузки" 
	dt_arrival_in_port_of_discharge,								-- SD.000059 "Дата прибытия в порт выгрузки" 
	dt_arrival_in_second_port_of_discharge,							-- SD.000060 "Дата прибытия в порт выгрузки 2" 
	delivery_basis,													-- SD.000067 "Базис поставки" 
	delivery_point_name,											-- SD.000068 "Пункт доставки по инкотермс" 
	dt_stamp_railway_bill,											-- SD.000071 "Дата штемпеля по ЖДН" 
	dt_plant_arrival,												-- SD.000072 "Дата прихода на завод" 
	dt_import_export_transfer,										-- SD.000073 "Дата перехода из импорта в экспорт" 
	contract_export_number,											-- SD.000078 "Внешнеторговый контракт завода" 
	dimensions_unit,												-- SD.000079 "Размер единицы готовой продукции" 
	consignee_name,													-- SD.000081 "Грузополучатель" 
	dt_customs_declaration,											-- SD.000088 "Дата ГТД"
	material_specification_name,									-- SD.000089 "Спецификация" 
	weight_strip,													-- SD.000090 "Вес ленты" 
	dt_quarantine_certificate,										-- SD.000095 "Дата карантинного сертификата" 
	dt_first_entry_appeared,										-- SD.000103 "Дата первого появления записи в системе" 
	dt_collection,													-- SD.000112 "Дата комплектования" 
	destination_station_in_shipment_name,							-- SD.000113 "Станция назначения в отгрузке" 
	dt_shipment_plan,												-- SD.000121 "Плановая дата отгрузки" 
	sales_order,													-- SD.000123 "Заказ ЦК" 
	dt_discharge_in_foreign_port,									-- SD.000128 "Дата выгрузки в порту" 
	dt_discharge_in_second_foreign_port,							-- SD.000129 "Дата выгрузки в порту 2" 	
	dt_arrival_in_port_of_discharge_plan,							-- SD.000130 "Дата прибытия в порт выгрузки план" 
	dt_delivery_notice,												-- SD.000132 "Дата нотиса о доставке" 
	material_code,													-- SD.000143 "Номер материала" 
	grade_name,														-- SD.000145 "Марка по спецификации" 
	dt_sales_order_delivery_actual,									-- SD.000146 "Фактическая дата получения заказа клиента" 
	dt_delivery_deadline,											-- SD.000149 "Deadline доставки" 
	shipment_period_preferred,										-- SD.000150 "Желаемый период отгрузки" 
	uni,															-- SD.000151 "UNI" 
	dt_arrival_in_second_port_of_discharge_plan,					-- SD.000157 "Дата прибытия в порт выгрузки 2 план" 
	dt_expected_delivery,											-- SD.000162 "Ожидаемая дата доставки до клиента" 
	end_user_name,													-- SD.000164 "Конечный потребитель" 
	quantity_shipped,												-- SD.000165 "Отгруженное количество" 
	quantity_ordered,												-- SD.000166 "Запланированное количество" 
	invoice_provisional_number,										-- SD.000167 "Инвойс (счет клиенту)" 
	invoice_final_number,											-- SD.000170 "Финальный счет" 
	dt_pledge_in,													-- SD.000173 "Дата pledge in" 
	production_order,												-- SD.000174 "Производственный заказ" 
	dt_storage_start_in_foreign_port,								-- SD.000175 "Дата начала хранения ин. склад" 
	dt_storage_end_in_foreign_port,									-- SD.000176 "Окончание хранения в ин. порту" 
	dt_storage_start_in_second_foreign_warehouse,					-- SD.000177 "Начало хранения склад 2" 
	dt_storage_end_in_second_foreign_warehouse,						-- SD.000178 "Окончание хранение склад 2" 
	material_shape_name_full,										-- SD.000180 "Форма"
	material_name,													-- SD.000200 "Наименование материала"	
	dt_realization_forecast, 										-- SD.000243 "Расчетная дата реализации" 
	realization_reason_document, 									-- SD.000245 "Основание реализации" 
	frame_contract_code,											-- SD.000246 "Рамочный контракт (код)" 
	dt_expected_bill_of_lading,										-- SD.000253 "Ожидаемая дата коносамента" 
	dt_release_material,											-- SD.000259 "Дата ОМ" 
	dt_etd,															-- SD.000261 "ETD Дата букинга" 
	delivery_region_name,											-- SD.000338 "Регион поставки по контракту" 
	dt_prepared_for_realization,									-- SD.000344 "Дата готовности к реализации" 
	dt_ownership_transfer,											-- SD.000375 "Дата перехода права собственности" 
	dt_final_release,												-- SD.000482 "Дата Финальный релиз" 
	railway_movement_status_name,									-- SD.000491 "Статус движения по ЖД" 
	business_location_name,											-- SD.000492 "Статус в Supply chain (Business)" 
	total_commitment_weight,										-- SD.000579 "Объем обязательств итого" 
	dt_warehouse_confirmation,										-- SD.000583 "Дата Storage confirmation" 
	dt_notice,														-- SD.000587 "Дата нотиса" 
	final_release_code,												-- SD.000588 "Номер Финальный релиз" 
	dt_final_invoice_payment,										-- SD.000589 "Дата оплаты Final Invoice" 
	country_of_end_user_name,										-- SD.000601 "Страна конечного потребителя" 
	dt_assignment,													-- SD.000606 "Дата поручения"
	vessel_and_voyage_plan_search_name,								-- SD.000607 "Судно / номер рейса (план)"	
	vessel_and_voyage_actual_search_name,							-- SD.000608 'Судно / номер рейса (факт)"	
	dt_storage_payed_in_foreign_port_by_rusal,						-- SD.000611 "Дата окончания хранения на складе за счет RUSAL по Релизу" 
	dt_shipment_instruction_in_foreign_port,						-- SD.000613 "Дата инструкции на отгрузку Ин Порт" 
	dt_shipment_instruction_date_from,								-- SD.000614 "SI: Дата с" 
	dt_shipment_instruction_date_to,								-- SD.000615 "SI: Дата по" 
	dt_barge_loading,												-- SD.000616 "Дата погрузки на баржу" 
	dt_barge_arrival,												-- SD.000617 "Дата доставки баржи" 
	dt_shipment_instruction_in_second_foreign_port,					-- SD.000619 "Дата инструкции на отгрузку Ин Порт 2" 
	dt_invoice_provisional,											-- SD.000620 "Дата инвойса" 
	dt_mh1_storage_document,										-- SD.000626 "Дата Акта МХ-1" 
	dt_mh3_storage_document,										-- SD.000628 "Дата Акта МХ-3" 
	dt_departure_from_foreigh_port									-- SD.000629 "EXP: Load out date" 
)
SELECT 
	dc_ssms.batch,													-- SD.000004 "Партия" 
	dc_ssms.sales_order_in_shipment,								-- SD.000005 "Заказ ЦК в отгрузке" 
	dc_ssms.plant_producer_code,									-- SD.000006 "Завод производитель (код)" 
	dc_ssms.plant_producer_name,									-- SD.000007 "Завод" 
	dc_ssms.tsw_location_name AS port_of_loading_name,				-- SD.000009 "Направление" 
	dc_ssms.dt_shipment,											-- SD.000010 "Дата отгрузки" 
	dc_ssms.dt_arrival_by_railway,									-- SD.000011 "Дата прибытия по ЖД" 
	dc_ssms.dt_forwarder,											-- SD.000012 "Дата экспедитора" 
	dc_ssms.material_aggr_name,										-- SD.000016 "Материал" 
	dc_ssms.material_group_code,									-- SD.000017 "Группа материалов" 
	dc_ssms.forwarder_name,											-- SD.000021 "Экспедитор" 
	dc_ssms.dt_warehouse,											-- SD.000024 "Дата склада" 
	dc_ssms.transport_railcar_type_name,							-- SD.000029 "Тип вагона" 
	dc_ssms.weight_gross,											-- SD.000031 "Вес брутто" 
	dc_ssms.weight_net,												-- SD.000032 "Вес нетто" 
	dc_ssms.weight_net_with_wirerod,								-- SD.000033 "Вес Н&K" 
	dc_ssms.customer_for_reporting_name 
		AS customer_for_reporting_name,								-- SD.000037 "Покупатель" 
	dc_ssms.contract_name, 											-- SD.000038 "Контракт" 
	dc_ssms.dt_bill_of_lading,										-- SD.000042 "Дата коносамента" 
	dc_ssms.dt_bill_of_lading_in_foreign_port,						-- SD.000049 "Дата коносамента в ин.порту" 
	dc_ssms.dt_sailed_loading_port,									-- SD.000058 "Дата отплытия из порта погрузки" 
	dc_ssms.dt_arrival_in_port_of_discharge,						-- SD.000059 "Дата прибытия в порт выгрузки" 
	dc_ssms.dt_arrival_in_second_port_of_discharge,					-- SD.000060 "Дата прибытия в порт выгрузки 2" 
	dc_ssms.delivery_basis,											-- SD.000067 "Базис поставки" 
	dc_ssms.delivery_point_name,									-- SD.000068 "Пункт доставки по инкотермс" 
	dc_ssms.dt_stamp_railway_bill,									-- SD.000071 "Дата штемпеля по ЖДН" 
	dc_ssms.dt_plant_arrival,										-- SD.000072 "Дата прихода на завод" 
	dc_ssms.dt_import_export_transfer,								-- SD.000073 "Дата перехода из импорта в экспорт" 
	dc_ssms.contract_export_number,									-- SD.000078 "Внешнеторговый контракт завода" 
	dc_ssms.dimensions_unit,										-- SD.000079 "Размер единицы готовой продукции" 
	dc_ssms.consignee_name,											-- SD.000081 "Грузополучатель" 
	dc_ssms.dt_customs_declaration,									-- SD.000088 "Дата ГТД"
	dc_ssms.material_specification_name,							-- SD.000089 "Спецификация" 
	dc_ssms.weight_strip,											-- SD.000090 "Вес ленты" 
	dc_ssms.dt_quarantine_certificate,								-- SD.000095 "Дата карантинного сертификата" 
	dc_ssms.dt_first_entry_appeared,								-- SD.000103 "Дата первого появления записи в системе" 
	dc_ssms.dt_collection,											-- SD.000112 "Дата комплектования" 
	dc_ssms.destination_station_in_shipment_name,					-- SD.000113 "Станция назначения в отгрузке" 
	dc_ssms.dt_shipment_plan,										-- SD.000121 "Плановая дата отгрузки" 
	dc_ssms.sales_order,											-- SD.000123 "Заказ ЦК" 
	dc_ssms.dt_discharge_in_foreign_port,							-- SD.000128 "Дата выгрузки в порту" 
	dc_ssms.dt_discharge_in_second_foreign_port,					-- SD.000129 "Дата выгрузки в порту 2" 	
	dc_ssms.dt_arrival_in_port_of_discharge_plan,					-- SD.000130 "Дата прибытия в порт выгрузки план" 
	dc_ssms.dt_delivery_notice,										-- SD.000132 "Дата нотиса о доставке" 
	dc_ssms.material_code,											-- SD.000143 "Номер материала" 
	dc_ssms.grade_name,												-- SD.000145 "Марка по спецификации" 
	dc_ssms.dt_sales_order_delivery_actual,							-- SD.000146 "Фактическая дата получения заказа клиента" 
	dc_ssms.dt_delivery_deadline,									-- SD.000149 "Deadline доставки" 
	dc_ssms.shipment_period_preferred,								-- SD.000150 "Желаемый период отгрузки" 
	dc_ssms.uni,													-- SD.000151 "UNI" 
	dc_ssms.dt_arrival_in_second_port_of_discharge_plan,			-- SD.000157 "Дата прибытия в порт выгрузки 2 план" 
	dc_ssms.dt_expected_delivery,									-- SD.000162 "Ожидаемая дата доставки до клиента" 
	dc_ssms.end_user_for_reporting_name 
		AS end_user_name,											-- SD.000164 "Конечный потребитель" 
	dc_ssms.quantity_shipped,										-- SD.000165 "Отгруженное количество" 
	dc_ssms.quantity_ordered,										-- SD.000166 "Запланированное количество" 
	dc_ssms.invoice_provisional_number,								-- SD.000167 "Инвойс (счет клиенту)" 
	dc_ssms.invoice_final_number,									-- SD.000170 "Финальный счет" 
	dc_ssms.dt_pledge_in,											-- SD.000173 "Дата pledge in" 
	dc_ssms.production_order,										-- SD.000174 "Производственный заказ" 
	dc_ssms.dt_storage_start_in_foreign_port,						-- SD.000175 "Дата начала хранения ин. склад" 
	dc_ssms.dt_storage_end_in_foreign_port,							-- SD.000176 "Окончание хранения в ин. порту" 
	dc_ssms.dt_storage_start_in_second_foreign_warehouse,			-- SD.000177 "Начало хранения склад 2" 
	dc_ssms.dt_storage_end_in_second_foreign_warehouse,				-- SD.000178 "Окончание хранение склад 2" 
	dc_ssms.material_shape_name_full,								-- SD.000180 "Форма"
	dc_ssms.material_name,											-- SD.000200 "Наименование материала"	
	dc_ssms.dt_realization_forecast, 								-- SD.000243 "Расчетная дата реализации" 
	dc_ssms.realization_reason_document, 							-- SD.000245 "Основание реализации" 
	dc_ssms.frame_contract_code,									-- SD.000246 "Рамочный контракт (код)" 
	dc_ssms.dt_expected_bill_of_lading,								-- SD.000253 "Ожидаемая дата коносамента" 
	dc_ssms.dt_release_material,									-- SD.000259 "Дата ОМ" 
	dc_ssms.dt_etd,													-- SD.000261 "ETD Дата букинга" 
	dc_ssms.delivery_region_name,									-- SD.000338 "Регион поставки по контракту" 
	dc_ssms.dt_prepared_for_realization,							-- SD.000344 "Дата готовности к реализации" 
	dc_ssms.dt_ownership_transfer,									-- SD.000375 "Дата перехода права собственности" 
	dc_ssms.dt_final_release,										-- SD.000482 "Дата Финальный релиз" 
	dc_ssms.railway_movement_status_name,							-- SD.000491 "Статус движения по ЖД" 
	dc_ssms.business_location_name,									-- SD.000492 "Статус в Supply chain (Business)" 
	dc_ssms.total_commitment_weight,								-- SD.000579 "Объем обязательств итого" 
	dc_ssms.dt_warehouse_confirmation,								-- SD.000583 "Дата Storage confirmation" 
	dc_ssms.dt_notice,												-- SD.000587 "Дата нотиса" 
	dc_ssms.final_release_code,										-- SD.000588 "Номер Финальный релиз" 
	dc_ssms.dt_final_invoice_payment,								-- SD.000589 "Дата оплаты Final Invoice" 
	dc_ssms.country_of_end_user_name,								-- SD.000601 "Страна конечного потребителя" 
	dc_ssms.dt_assignment,											-- SD.000606 "Дата поручения"
	dc_ssms.vessel_and_voyage_plan_search_name,						-- SD.000607 "Судно / номер рейса (план)"	
	dc_ssms.vessel_and_voyage_actual_search_name,					-- SD.000608 'Судно / номер рейса (факт)"	
	dc_ssms.dt_storage_payed_in_foreign_port_by_rusal,				-- SD.000611 "Дата окончания хранения на складе за счет RUSAL по Релизу" 
	dc_ssms.dt_shipment_instruction_in_foreign_port,				-- SD.000613 "Дата инструкции на отгрузку Ин Порт" 
	dc_ssms.dt_shipment_instruction_date_from,						-- SD.000614 "SI: Дата с" 
	dc_ssms.dt_shipment_instruction_date_to,						-- SD.000615 "SI: Дата по" 
	dc_ssms.dt_barge_loading,										-- SD.000616 "Дата погрузки на баржу" 
	dc_ssms.dt_barge_arrival,										-- SD.000617 "Дата доставки баржи" 
	dc_ssms.dt_shipment_instruction_in_second_foreign_port,			-- SD.000619 "Дата инструкции на отгрузку Ин Порт 2" 
	dc_ssms.dt_invoice_provisional,									-- SD.000620 "Дата инвойса" 
	dc_ssms.dt_mh1_storage_document,								-- SD.000626 "Дата Акта МХ-1" 
	dc_ssms.dt_mh3_storage_document,								-- SD.000628 "Дата Акта МХ-3" 
	dc_ssms.dt_departure_from_foreigh_port							-- SD.000629 "EXP: Load out date" 
FROM 
	dm_calc.sd_sales_main_scm AS dc_ssms
;