LEAGUE_OUTCOME_RULES = {
    39: {  # Premier League
        "ev_A": 0.16,
        "ev_B": 0.08,
        "min_odds_A": 1.90,
        "max_odds_A": 2.20,
        "min_odds_B": 2.00,
        "max_odds_B": 3.00,
        "draw_min_odds_A": 3.00,
        "draw_max_odds_A": 5.00,
        "draw_min_odds_B": 3.00,
        "draw_max_odds_B": 5.00,
        "allow_draw": True,
    },
    61: {  # Ligue 1
        "ev_A": 0.10,
        "ev_B": 0.06,
        "min_odds_A": 1.50,
        "max_odds_A": 2.40,
        "min_odds_B": 1.40,
        "max_odds_B": 3.20,
        "draw_min_odds_A": 2.80,
        "draw_max_odds_A": 4.50,
        "draw_min_odds_B": 2.80,
        "draw_max_odds_B": 4.50,
        "allow_draw": True,
    },
    78: {  # Bundesliga
        "ev_A": 0.06,
        "ev_B": 0.02,
        "min_odds_A": 2.00,
        "max_odds_A": 2.40,
        "min_odds_B": 1.80,
        "max_odds_B": 3.00,
        "draw_min_odds_A": 3.00,
        "draw_max_odds_A": 5.00,
        "draw_min_odds_B": 3.00,
        "draw_max_odds_B": 5.00,
        "allow_draw": True,
    },
    135: {  # Serie A
        "ev_A": 0.06,
        "ev_B": 0.02,
        "min_odds_A": 1.50,
        "max_odds_A": 2.40,
        "min_odds_B": 2.00,
        "max_odds_B": 3.00,
        "draw_min_odds_A": 3.00,
        "draw_max_odds_A": 5.00,
        "draw_min_odds_B": 3.00,
        "draw_max_odds_B": 5.00,
        "allow_draw": True,
    },
    140: {  # La Liga
        "ev_A": 0.20,
        "ev_B": 0.16,
        "min_odds_A": 1.50,
        "max_odds_A": 3.00,
        "min_odds_B": 2.20,
        "max_odds_B": 2.60,
        "draw_min_odds_A": 2.60,
        "draw_max_odds_A": 4.00,
        "draw_min_odds_B": 2.60,
        "draw_max_odds_B": 4.00,
        "allow_draw": True,
    },
}

DEFAULT_OUTCOME_RULE = {
    "ev_A": 0.20,
    "ev_B": 0.16,
    "min_odds_A": 1.90,
    "max_odds_A": 2.50,
    "min_odds_B": 2.10,
    "max_odds_B": 2.80,
    "allow_draw": False,
}
