INSERT INTO STG."/RUSAL/LEPORT"
( "MANDT", "BL", "DATABL", "CONTAINER", "TRATY", "PORT_FROM", "PORT_TO", "ROUTE", "TERMINAL_TO", "EXPED_PORT", "EXPED_FREIGHT", "DATA_SHIP", "DATAOT", "NAKLADN", "VAGON", "OWNER_PLATF", "AUTO", "VBELN_LE", "ERDAT", "ERZET", "ERNAM", "AEDAT", "AEZET", "AENAM", "TERMINAL_RF", "DATAVP", "DATADU", "DU", "BL_FIRST", "RN")
SELECT "MANDT", "BL", "DATABL", "CONTAINER", "TRATY", "PORT_FROM", "PORT_TO", "ROUTE", "TERMINAL_TO", "EXPED_PORT", "EXPED_FREIGHT", "DATA_SHIP", "DATAOT", "NAKLADN", "VAGON", "OWNER_PLATF", "AUTO", "VBELN_LE", "ERDAT", "ERZET", "ERNAM", "AEDAT", "AEZET", "AENAM", "TERMINAL_RF", "DATAVP", "DATADU", "DU", "BL_FIRST", "RN"
FROM raw_ext."/RUSAL/LEPORT_READ";
