insert into dm.alverse_transportation_life_cycle(
	initial_delivery_code,
	initial_delivery_item_code,
	sales_order_code,
	expense_account_code,
	expense_account_name,
	expense_account_search_name,
	sales_bundle_gross_weight,
	sales_bundle_net_weight,
	total_expense_per_gross_weight_usd_amount,
	total_expense_per_net_weight_usd_amount,
	plant_producer_search_name,
	transport_type_search_name,
	transport_vehicle_code,
	transport_bill_code,
	transport_bill_and_railcar_uni_code,
	etsng_search_name,
	material_search_name,
	shape_search_name,
	sector_search_name,
	grade_search_name,
	supplier_search_name,
	transport_subtype_search_name,
	expense_translated_currency_code,
	expense_group_search_name,
	transportation_service_contract_code,
	transportation_scheme_search_name,
	transportation_scheme_type_search_name,
	transportation_scheme_subtype_search_name,
	external_contract_number
)
select
	initial_delivery_code,
	initial_delivery_item_code,
	sales_order_code,
	expense_account_code,
	expense_account_name,
	expense_account_search_name,
	min(sum_sales_bundle_gross_weight) / 1000 as sales_bundle_gross_weight,
	min(sum_sales_bundle_net_weight) / 1000 as sales_bundle_net_weight,
	sum(total_expense_per_gross_weight_usd_amount) as total_expense_per_gross_weight_usd_amount,
	sum(total_expense_per_net_weight_usd_amount) as total_expense_per_net_weight_usd_amount,
	min(plant_producer_search_name) as plant_producer_search_name,
	min(transport_type_search_name) as transport_type_search_name,
	min(transport_vehicle_code) as transport_vehicle_code,
	min(transport_bill_code) as transport_bill_code,
	min(transport_bill_and_railcar_uni_code) as transport_bill_and_railcar_uni_code,
	min(etsng_search_name) as etsng_search_name,
	min(material_search_name) as material_search_name,
	min(shape_search_name) as shape_search_name,
	min(sector_search_name) as sector_search_name,
	min(grade_search_name) as grade_search_name,
	min(supplier_search_name) as supplier_search_name,
	min(transport_subtype_search_name) as transport_subtype_search_name,
	min(expense_translated_currency_code) as expense_translated_currency_code,
	min(expense_group_search_name) as expense_group_search_name,
	min(transportation_service_contract_code) as transportation_service_contract_code,
	min(transportation_scheme_search_name) as transportation_scheme_search_name,
	min(transportation_scheme_type_search_name) as transportation_scheme_type_search_name,
	min(transportation_scheme_subtype_search_name) as transportation_scheme_subtype_search_name,
	min(external_contract_number) as external_contract_number
from
	dm_calc.alverse_transportation_life_cycle
group by initial_delivery_code, initial_delivery_item_code, sales_order_code, expense_account_code, expense_account_name, expense_account_search_name
having
	sum(total_expense_per_gross_weight_usd_amount) <> 0
	or sum(total_expense_per_net_weight_usd_amount) <> 0;