insert into ods."/rusal/perp_ral" (
	werks,
	id,
	pos,
	srvpos,
	nomd,
	sums,
	nds,
	waers,
	akt_id,
	fistl,
	etsng,
	ebelny,
	doc_type,
	check_tarif,
	statuss,
	aufnr,
	belnr,
	charg,
	check_off,
	check_off_dub,
	hkont,
	hranenie_from,
	hranenie_to,
	fi_112,
	fi_137,
	kostl,
	kunnr,
	matnr,
	request,
	vatcl,
	kontyp,
	manual_aufnr,
	manual_hkont,
	manual_kontyp,
	manual_kostl,
	manual_kunnr,
	manual_mwskz,
	manual_pspnr,
	manual_vatcl,
	pspnr,
	fipos_manual,
	fistl_manual,
	bwtar,
	route,
	mwskz,
	kor,
	nds_nvv,
	type_prod,
	check_off_limit,
	ebelnz
)
select
	tech_etl.util_text_to_null_validation(perp."WERKS") as werks,
	tech_etl.util_text_to_null_validation(perp."ID") as id,
	tech_etl.util_text_to_null_validation(perp."POS") as pos,
	tech_etl.util_text_to_null_validation(perp."SRVPOS") as srvpos,
	tech_etl.util_text_to_null_validation(perp."NOMD") as nomd,
	perp."SUMS" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as sums,
	perp."NDS" * (10 ^ (2 - coalesce(dp.decimal_place_number, 2))) as nds,	
	tech_etl.util_text_to_null_validation(perp."WAERS") as waers,
	tech_etl.util_text_to_null_validation(perp."AKT_ID") as akt_id,
	tech_etl.util_text_to_null_validation(perp."FISTL") as fistl,
	tech_etl.util_text_to_null_validation(perp."ETSNG") as etsng,
	tech_etl.util_text_to_null_validation(perp."EBELNY") as ebelny,
	tech_etl.util_text_to_null_validation(perp."DOC_TYPE") as doc_type,
	tech_etl.util_text_to_null_validation(perp."CHECK_TARIF") as check_tarif,
	tech_etl.util_text_to_null_validation(perp."STATUSS") as statuss,
	tech_etl.util_text_to_null_validation(perp."AUFNR") as aufnr,
	tech_etl.util_text_to_null_validation(perp."BELNR") as belnr,
	tech_etl.util_text_to_null_validation(perp."CHARG") as charg,
	tech_etl.util_text_to_null_validation(perp."CHECK_OFF") as check_off,
	tech_etl.util_text_to_null_validation(perp."CHECK_OFF_DUB") as check_off_dub,
	tech_etl.util_text_to_null_validation(perp."HKONT") as hkont,
	tech_etl.util_text_to_date_validation(perp."HRANENIE_FROM") as hranenie_from,
	tech_etl.util_text_to_date_validation(perp."HRANENIE_TO") as hranenie_to,
	tech_etl.util_text_to_null_validation(perp."FI_112") as fi_112,
	tech_etl.util_text_to_null_validation(perp."FI_137") as fi_137,
	tech_etl.util_text_to_null_validation(perp."KOSTL") as kostl,
	tech_etl.util_text_to_null_validation(perp."KUNNR") as kunnr,
	tech_etl.util_text_to_null_validation(perp."MATNR") as matnr,
	tech_etl.util_text_to_null_validation(perp."REQUEST") as request,
	tech_etl.util_text_to_null_validation(perp."VATCL") as vatcl,
	tech_etl.util_text_to_null_validation(perp."KONTYP") as kontyp,
	tech_etl.util_text_to_null_validation(perp."MANUAL_AUFNR") as manual_aufnr,
	tech_etl.util_text_to_null_validation(perp."MANUAL_HKONT") as manual_hkont,
	tech_etl.util_text_to_null_validation(perp."MANUAL_KONTYP") as manual_kontyp,
	tech_etl.util_text_to_null_validation(perp."MANUAL_KOSTL") as manual_kostl,
	tech_etl.util_text_to_null_validation(perp."MANUAL_KUNNR") as manual_kunnr,
	tech_etl.util_text_to_null_validation(perp."MANUAL_MWSKZ") as manual_mwskz,
	tech_etl.util_text_to_null_validation(perp."MANUAL_PSPNR") as manual_pspnr,
	tech_etl.util_text_to_null_validation(perp."MANUAL_VATCL") as manual_vatcl,
	tech_etl.util_text_to_null_validation(perp."PSPNR") as pspnr,
	tech_etl.util_text_to_null_validation(perp."FIPOS_MANUAL") as fipos_manual,
	tech_etl.util_text_to_null_validation(perp."FISTL_MANUAL") as fistl_manual,
	tech_etl.util_text_to_null_validation(perp."BWTAR") as bwtar,
	tech_etl.util_text_to_null_validation(perp."ROUTE") as route,
	tech_etl.util_text_to_null_validation(perp."MWSKZ") as mwskz,
	tech_etl.util_text_to_null_validation(perp."KOR") as kor,
	tech_etl.util_text_to_null_validation(perp."NDS_NVV") as nds_nvv,
	tech_etl.util_text_to_null_validation(perp."TYPE_PROD") as type_prod,
	tech_etl.util_text_to_null_validation(perp."CHECK_OFF_LIMIT") as check_off_limit,
	tech_etl.util_text_to_null_validation(perp."EBELNZ") as ebelnz
from stg."/RUSAL/PERP" as perp
	left join dict_dds.currency_decimal_place_ral as dp			---джойн с TCURX RAL
		on dp.currency_code = perp."WAERS"
where perp."MANDT" = '400';
