select tech_etl.etl_source_to_greenplum_new(
        v_source_schema_name := 'SAPSR3',
        v_source_table_name := 'ZFI3436M_BI2',
        v_fields_list := 'KUNNRKEY,VERTNKEY,FO_VBELNKEY,FO_POSNRKEY,ZP_TRADER,ZP_ZAKAZ_KL,ZP_WERKS,ZP_WERKS_NAME,ZP_TRANSPORT,ZP_WEIGHT_BASE,ZP_ZPEREV,ZP_GRUZPOL,ZP_GRUZPOL_NAME,ZP_QUOTA,ZP_ERNAM,ZP_ZTERM,ZP_ZTERM_NAME,ZP_ZTERM_DATE,ZP_GRUZOTP,R_AUDAT,R_INCO1,R_ZZPEREV,FO_BUKRS,FO_WERKS,FO_KVGR2,FO_VERTN_A,FO_ERDAT,FO_KODAT,FO_LDDAT,FO_LDDAT_5,FO_WADAT_IST,FO_LIFNR,FO_WAGTYPE,FO_VAGON,FO_GRUZ,FO_NAKLADN,FO_MATNR_MFR,FO_PRSDT,FO_KBETR,FO_KOEI1,FO_WAERS,FO_KURSF,FO_NK,FO_VBELN_ZV,FO_POSNR_ZV,FO_VBELN_IN,FO_CHARG,FO_WBSTA,PP_FO_ID,PP_FO_HWAER,PP_FO_HWAE2,V_BELNR,V_GJAHR,V_BELNR_S',	
        v_target_schema_name := 'STG',
        v_target_table_name := 'ZFI3436M_BI2',
        v_server_id := 1,
        v_distribution_field := 'RN',
        v_pk := '"KUNNRKEY" || "VERTNKEY" || "FO_VBELNKEY" || "FO_POSNRKEY"'
);