INSERT INTO stg."/RUSAL/IMTZR" ("MANDT", "REPCOD", "BUKRS", "WERKS", "GJAHR", "PERIO", "LNCOD", "CLCOD", "TZRTP", "SAKNR", "GKONT",
"KSTAR", "WRTTP", "EBELN", "LIFNR", "SHKZG", "BWAGR", "WERKS_S", "WOGBTR", "WKGBTR", "EBELNY","INDX",
"RN") 
SELECT "MANDT", "REPCOD", "BUKRS", "WERKS", "GJAHR", "PERIO", "LNCOD", "CLCOD", "TZRTP", "SAKNR", "GKONT",
"KSTAR", "WRTTP", "EBELN", "LIFNR", "SHKZG", "BWAGR", "WERKS_S", "WOGBTR", "WKGBTR", "EBELNY","INDX",
"RN" FROM raw_ext."/RUSAL/IMTZR_READ";