insert into ods.map_sales_shipment_from_rus_port_act_vs_plan_dob_dkp_keys(
    sales_market_code,
	dt_shipment_from_russian_port_plan_yyyymm,
	report_row_identification_code,
	railcar_plan_number,
	railcar_from_plant_code,
	railcar_transshipped_code,
	tsw_location_code,
	transport_type_from_plant_code,
	vessel_code,
	dt_bill_of_lading_expected,
	dt_bill_of_lading_actual,
	port_of_discharge_code,
	quota_period_yyyymm,
	sales_order_code,
	net_weight_with_wirerod_plan,
	dt_shipment_from_plant_actual,
	dt_shipment_from_plant_plan,
	dt_actual_shipment_from_russian_port,
	bill_of_lading_in_russian_port_code,
	forwarder_comment,
	forwarder_code,
	sea_forwarder_code,
	storage_duration_in_russian_port_in_calendar_days,
	dt_arrival_to_port_of_discharge_plan,
	dt_arrival_to_port_of_discharge_actual,
	transport_type_after_repackaging_code,
	dt_etd_departure_from_russian_port_plan,
	dt_etd_departure_from_russian_port_actual,
	is_empty_dt_bill_of_lading_expected,
	official_note_for_unplanned_shipment_number,
	dt_official_note_for_unplanned_shipment,
	dt_saved_in_sap_system,
	nomination_actual_code,
	metal_owner_code,
	dt_arrival_by_railway,
	consignee_code,
	is_loaded_and_shipped_in_multiple_month,
	nomination_plan_code,
	is_shipped_via_official_note,
	sales_delivery_code,
	batch_code,
	transport_bill_code,
	uni,
	material_code,
	is_tsw_location_code_changed,
	tsw_location_name,
	buyer_for_reporting_code,
	buyer_for_reporting_name,
	adjustment_difference_weight,
	actual_total_weight,
	shipment_plan_weight,
	shipment_left_plan_weight,
	comment_of_sales,
	comment_of_transportation,
	is_responsibility_of_sales,
	is_responsibility_of_transportation,
	forwarder_name,
	sea_forwarder_name,
	booked_for_shipment_weight,
	transport_type_actual_name,
	transport_type_plan_code,
	transport_type_plan_name,
	report_date_actual_total_weight,
	report_date_plan_weight,
	material_name,
	dt_bill_of_lading_plan,
	transport_type_after_repackaging_name,
	business_location_name,
	initial_appearance_version_code,
	final_plan_weight,
	final_adjustment_plan_weight,
	final_unplanned_weight,
	dt_plan_version_saved,
	dt_plan_version_finalized,
	according_to_plan_shipped_actual_weight,
	according_to_adjusted_plan_shipped_actual_weight,
	dt_delivery_due_date,
	delivery_route_code,
	shipped_actual_total_weight,
	according_to_adjusted_plan_shipped_actual_total_weight,
	shipped_unplanned_actual_weight,
	dt_official_note_created,
	official_note_created_by,
	official_note_approval_status_code,
	official_note_approval_status_name,
	official_note_status_code,
	official_note_nomination_code,
	dt_official_note_bill_of_lading_expected,
	official_note_approved_by,
	dt_official_note_approved,
	official_note_weight,
	plan_exceed_weight,
	official_note_declined_weight,
	plan_total_weight,
	period_transferred_weight,
	dt_report
)
select 
    tech_etl.util_text_to_null_validation("MARKET") as sales_market_code,
    tech_etl.util_text_to_null_validation("POPER") as dt_shipment_from_russian_port_plan_yyyymm,
    tech_etl.util_text_to_null_validation("GUID_KEY") as report_row_identification_code,
    tech_etl.util_text_to_null_validation("VAGON_PLAN") as railcar_plan_number,
    tech_etl.util_text_to_null_validation("VAGON") as railcar_from_plant_code,
    tech_etl.util_text_to_null_validation("VAGON_PR") as railcar_transshipped_code,
    tech_etl.util_text_to_null_validation("LOCID") as tsw_location_code,
    tech_etl.util_text_to_null_validation("SDABW") as transport_type_from_plant_code,
    tech_etl.util_text_to_null_validation("VEH_TEXT") as vessel_code,
    tech_etl.util_text_to_date_validation("ETAR") as dt_bill_of_lading_expected,
    tech_etl.util_text_to_date_validation("KONOSDATE") as dt_bill_of_lading_actual,
    tech_etl.util_text_to_null_validation("BEZEI_END") as port_of_discharge_code,
    tech_etl.util_text_to_null_validation("QUOTA") as quota_period_yyyymm,
    tech_etl.util_text_to_null_validation("ZAKAZ_KL") as sales_order_code,
    "VES_WAG_P" as net_weight_with_wirerod_plan,
    tech_etl.util_text_to_date_validation("D_WERKS_OTGR") as dt_shipment_from_plant_actual,
    tech_etl.util_text_to_date_validation("D_WERKS_OTGR_P") as dt_shipment_from_plant_plan,
    tech_etl.util_text_to_date_validation("SAILED_L_PORT") as dt_actual_shipment_from_russian_port,
    tech_etl.util_text_to_null_validation("KONOSAMENT") as bill_of_lading_in_russian_port_code,
    tech_etl.util_text_to_null_validation("COMMENTS") as forwarder_comment,
    tech_etl.util_text_to_null_validation("EXPEDID") as forwarder_code,
    tech_etl.util_text_to_null_validation("SEALINE") as sea_forwarder_code,
    "STORAGE" as storage_duration_in_russian_port_in_calendar_days,
    tech_etl.util_text_to_date_validation("D_PORT_ARRIV_PL") as dt_arrival_to_port_of_discharge_plan,
    tech_etl.util_text_to_date_validation("D_PORT_ARRIV") as dt_arrival_to_port_of_discharge_actual,
    tech_etl.util_text_to_null_validation("SDABW_PERETARKA") as transport_type_after_repackaging_code,
    tech_etl.util_text_to_date_validation("ETD_L_PORT") as dt_etd_departure_from_russian_port_plan,
    tech_etl.util_text_to_date_validation("BOOKING_DATE") as dt_etd_departure_from_russian_port_actual,
    tech_etl.util_text_to_null_validation("WITHOUT_E_BL") as is_empty_dt_bill_of_lading_expected,
    tech_etl.util_text_to_null_validation("OFFIC_MEMO") as official_note_for_unplanned_shipment_number,
    tech_etl.util_text_to_date_validation("DATE_MEMO") as dt_official_note_for_unplanned_shipment,
    tech_etl.util_text_to_time_validation("SAVTM") as dt_saved_in_sap_system,
    tech_etl.util_text_to_null_validation("NOMTK") as nomination_actual_code,
    tech_etl.util_text_to_null_validation("WERKSP") as metal_owner_code,
    tech_etl.util_text_to_date_validation("DATAPRZD") as dt_arrival_by_railway,
    tech_etl.util_text_to_null_validation("FIRMAPID") as consignee_code,
    tech_etl.util_text_to_null_validation("PNSM") as is_loaded_and_shipped_in_multiple_month,
    tech_etl.util_text_to_null_validation("NOMTK_RA") as nomination_plan_code,
    tech_etl.util_text_to_null_validation("ADD_BY_OM") as is_shipped_via_official_note,
    tech_etl.util_text_to_null_validation("VBELN") as sales_delivery_code,
    tech_etl.util_text_to_null_validation("CHARG") as batch_code,
    tech_etl.util_text_to_null_validation("NAKLADN") as transport_bill_code,
    tech_etl.util_text_to_null_validation("UNI") as uni,
    tech_etl.util_text_to_null_validation("MATNR") as material_code,
    tech_etl.util_text_to_null_validation("CLOCID") as is_tsw_location_code_changed,
    tech_etl.util_text_to_null_validation("LOCNAM") as tsw_location_name,
    tech_etl.util_text_to_null_validation("BUYER") as buyer_for_reporting_code,
    tech_etl.util_text_to_null_validation("BUYER_TXT") as buyer_for_reporting_name,
    "VES_WAG_P_CORR" as adjustment_difference_weight,
    "VES_WAG_FIN" as actual_total_weight,
    "DEV" as shipment_plan_weight,
    "DEV2" as shipment_left_plan_weight,
    tech_etl.util_text_to_null_validation("COMMENTS_SALES") as comment_of_sales,
    tech_etl.util_text_to_null_validation("COMMENTS_DTL") as comment_of_transportation,
    tech_etl.util_text_to_null_validation("RESPONSIB_SALES") as is_responsibility_of_sales,
    tech_etl.util_text_to_null_validation("RESPONSIB_DTL") as is_responsibility_of_transportation,
    tech_etl.util_text_to_null_validation("EXPEDID_TXT") as forwarder_name,
    tech_etl.util_text_to_null_validation("SEALINE_TXT") as sea_forwarder_name,
    "VES_WAG" as booked_for_shipment_weight,
    tech_etl.util_text_to_null_validation("SDABW_TXT") as transport_type_actual_name,
    tech_etl.util_text_to_null_validation("SDABW_PREV") as transport_type_plan_code,
    tech_etl.util_text_to_null_validation("SDABW_PREV_TXT") as transport_type_plan_name,
    "VES_WAG_P_NEW" as report_date_actual_total_weight,
    "VES_WAG_PC_NEW" as report_date_plan_weight,
    tech_etl.util_text_to_null_validation("MATNR_NAME") as material_name,
    tech_etl.util_text_to_date_validation("PLAN_BL") as dt_bill_of_lading_plan,
    tech_etl.util_text_to_null_validation("SDABW_PERETARKA_TXT") as transport_type_after_repackaging_name,
    tech_etl.util_text_to_null_validation("STATUS_TXT") as business_location_name,
    tech_etl.util_text_to_null_validation("CUT_PRIZN") as initial_appearance_version_code,
    "VES_WAG_PC" as final_plan_weight,
    "VES_WAG_PC_CORR" as final_adjustment_plan_weight,
    "VES_WAG_PC_FIN" as final_unplanned_weight,
    tech_etl.util_text_to_date_validation("PLAN_DATE") as dt_plan_version_saved,
    tech_etl.util_text_to_date_validation("CORR_DATE") as dt_plan_version_finalized,
    "VES_WAG_FACT" as according_to_plan_shipped_actual_weight,
    "VES_WAG_P_FACT" as according_to_adjusted_plan_shipped_actual_weight,
    tech_etl.util_text_to_date_validation("LFDAT") as dt_delivery_due_date,
    tech_etl.util_text_to_null_validation("ROUTE") as delivery_route_code,
    "VES_WAG_FACT_PC" as shipped_actual_total_weight,
    "VES_WAG_P_FACT_PC" as according_to_adjusted_plan_shipped_actual_total_weight,
    "VES_WAG_PV_FACT_PC" as shipped_unplanned_actual_weight,
    tech_etl.util_text_to_time_validation("TIME_MEMO") as dt_official_note_created,
    tech_etl.util_text_to_null_validation("USER_MEMO") as official_note_created_by,
    tech_etl.util_text_to_null_validation("STATUS_MEMO") as official_note_approval_status_code,
    tech_etl.util_text_to_null_validation("STATUS_MEMO_TXT") as official_note_approval_status_name,
    tech_etl.util_text_to_null_validation("MEMO_STATUS") as official_note_status_code,
    tech_etl.util_text_to_null_validation("NOMTK_MEMO") as official_note_nomination_code,
    tech_etl.util_text_to_date_validation("ETAR_MEMO") as dt_official_note_bill_of_lading_expected,
    tech_etl.util_text_to_null_validation("APPROVEDBY") as official_note_approved_by,
    tech_etl.util_text_to_date_validation("APPROVALDATE") as dt_official_note_approved,
    "MEMO_WEIGHT" as official_note_weight,
    "OVERPLAN" as plan_exceed_weight,
    "DECL_WEIGHT" as official_note_declined_weight,
    "PLAN_TOTAL" as plan_total_weight,
    "DELETED_MEMO" as period_transferred_weight,
    tech_etl.util_text_to_date_validation("REPDATE") as dt_report --2025.09.12 добавила
from stg."ZTSD2902M_L_KHD"
where "MANDT" = '400'
  and tech_etl.util_text_to_date_validation("POPER" || '01') between date_trunc('month', current_date - interval '1 month') and date_trunc('month', current_date + interval '1 month');