insert into dm_calc.raw_materials_shipment_and_arrival (
	transport_bill_code,
	railcar_code,
	transport_bill_and_railcar_code,
	departure_type_code,
	departure_type_name,
	dt_shipping,
	dt_departure,
	russian_port_pier_code,
	russian_port_code,
	russian_port_terminal_code,
	supplier_code,
	producer_code,
	business_scheme_type_code,
	package_type_code,
	material_code,
	railway_station_of_departure_code,
	plant_of_departure_code,
	railway_station_of_destination_code,
	plant_of_destination_code,
	warehouse_code,
	railway_track_at_plant_number,
	dt_discharge,
	dt_posting,
	purchase_contract_code,
	import_method_code,
	is_compound_cargo,
	etsng_code,
	transport_type_code,
	railcar_capacity,
	redirection_type_code,
	dt_redirected,
	redirection_created_by_code,
	transport_bill_after_redirection_code,
	dt_shipment_after_redirection,
	station_of_destination_after_redirection_code,
	station_of_destination_before_redirection_code,
	plant_of_destination_before_redirection_code,
	dt_train_operation,
	dislocation_railcar_operation_code,
	dislocation_station_of_departure_code,
	dislocation_station_of_destination_code,
	dislocation_station_current_code,
	distance_left_to_destination_kilometer_quantity,
	dt_dislocation_arrival_to_destination_station,
	dt_dislocation_estimated_arrival_to_destination_station,
	dt_vessel_arrival_to_russian_port,
	dt_vessel_discharge_in_russian_port,
	dt_arrival_to_destination_station,
	dt_zdc_arrival_to_destination_station,
	dt_arrival_by_accounting,
	vessel_code,
	bill_of_lading_number,
	delivery_code,
	dt_general_act,
	weight_net
)
with cte as (
	select
		transport_bill_code,
		railcar_code,
		transport_bill_and_railcar_code,
		supplier_code,
		producer_code,
		business_scheme_type_code,
		dt_arrival_by_accounting,
		dt_discharge,
		dt_posting,
		warehouse_code,
		railway_track_at_plant_number,
		purchase_contract_code,
		bill_of_lading_number,
		dense_rank() over (partition by transport_bill_and_railcar_code order by dt_arrival_by_accounting desc)  as rwn1,	
		sum(weight_net) as weight_net
	from dm_calc.raw_materials_arrival
	group by
		transport_bill_code,
		railcar_code,
		transport_bill_and_railcar_code,
		supplier_code,
		producer_code,
		business_scheme_type_code,
		dt_arrival_by_accounting,
		dt_discharge,
		dt_posting,
		warehouse_code,
		railway_track_at_plant_number,
		purchase_contract_code,
		bill_of_lading_number
)
select
	shipment.transport_bill_code,
	shipment.railcar_code,
	shipment.transport_bill_and_railcar_code,
	shipment.departure_type_code,
	shipment.departure_type_name,
	shipment.dt_shipping,
	shipment.dt_departure,
	shipment.russian_port_pier_code,
	shipment.russian_port_code,
	shipment.russian_port_terminal_code,
	coalesce(arrival.supplier_code, shipment.supplier_code) as supplier_code,
	coalesce(arrival.producer_code, shipment.producer_code) as producer_code,
	coalesce(arrival.business_scheme_type_code, shipment.business_scheme_type_code) as business_scheme_type_code,
	shipment.package_type_code,
	shipment.material_code,
	shipment.railway_station_of_departure_code,
	shipment.plant_of_departure_code,
	shipment.railway_station_of_destination_code as railway_station_of_destination_code,
	shipment.plant_of_destination_code,
	arrival.warehouse_code,
	arrival.railway_track_at_plant_number,
	arrival.dt_discharge,
	arrival.dt_posting,
	arrival.purchase_contract_code,
	shipment.import_method_code,
	shipment.is_compound_cargo,
	shipment.etsng_code,
	shipment.transport_type_code,
	shipment.railcar_capacity,
	shipment.redirection_type_code,
	shipment.dt_redirected,
	shipment.redirection_created_by_code,
	shipment.transport_bill_after_redirection_code,
	shipment.dt_shipment_after_redirection,
	shipment.station_of_destination_after_redirection_code,
	shipment.station_of_destination_before_redirection_code,
	shipment.plant_of_destination_before_redirection_code,
	shipment.dt_train_operation,
	shipment.dislocation_railcar_operation_code,
	shipment.dislocation_station_of_departure_code,
	shipment.dislocation_station_of_destination_code,
	shipment.dislocation_station_current_code,
	shipment.distance_left_to_destination_kilometer_quantity,
	shipment.dt_dislocation_arrival_to_destination_station,
	shipment.dt_dislocation_estimated_arrival_to_destination_station,
	shipment.dt_vessel_arrival_to_russian_port,
	shipment.dt_vessel_discharge_in_russian_port,
	shipment.dt_arrival_to_destination_station,
	shipment.dt_zdc_arrival_to_destination_station,
	coalesce(arrival.dt_arrival_by_accounting, shipment.dt_arrival_by_accounting) as dt_arrival_by_accounting,
	shipment.vessel_code,
	shipment.bill_of_lading_number,
	shipment.delivery_code,
	shipment.dt_general_act,
	coalesce(arrival.weight_net, shipment.weight_net) as weight_net
from dm_calc.raw_materials_shipment as shipment
	left join cte as arrival
		on shipment.transport_bill_code = arrival.transport_bill_code and
		   shipment.railcar_code = arrival.railcar_code and
		   coalesce(shipment.bill_of_lading_number, '') = coalesce(arrival.bill_of_lading_number, shipment.bill_of_lading_number, '') and 
		   arrival.rwn1 = 1
;