INSERT INTO stg."KONP" ("MANDT", "KNUMH", "KOPOS", "KAPPL", "KSCHL", "KNUMT", "STFKZ", "KZBZG", "KSTBM", "KONMS", "KSTBW",
"KONWS", "KRECH", "KBETR", "KONWA", "KPEIN", "KMEIN", "PRSCH", "KUMZA", "KUMNE", "MEINS",
"MXWRT", "GKWRT", "PKWRT", "FKWRT", "RSWRT", "KWAEH", "UKBAS", "KZNEP", "KUNNR", "LIFNR",
"MWSK1", "LOEVM_KO", "ZAEHK_IND", "BOMAT", "KBRUE", "KSPAE", "BOSTA", "KNUMA_PI", "KNUMA_AG", "KNUMA_SQ",
"VALTG", "VALDT", "ZTERM", "ANZAUF", "MIKBAS", "MXKBAS", "KOMXWRT", "KLF_STG", "KLF_KAL", "VKKAL",
"AKTNR", "KNUMA_BO", "MWSK2", "VERTT", "VERTN", "VBEWA", "MDFLG", "KFRST", "UASTA", "/BEV1/ECRTT",
"/BEV1/ECRTN", "/BEV1/ECEWA", "RN") 
SELECT "MANDT", "KNUMH", "KOPOS", "KAPPL", "KSCHL", "KNUMT", "STFKZ", "KZBZG", "KSTBM", "KONMS", "KSTBW",
"KONWS", "KRECH", "KBETR", "KONWA", "KPEIN", "KMEIN", "PRSCH", "KUMZA", "KUMNE", "MEINS",
"MXWRT", "GKWRT", "PKWRT", "FKWRT", "RSWRT", "KWAEH", "UKBAS", "KZNEP", "KUNNR", "LIFNR",
"MWSK1", "LOEVM_KO", "ZAEHK_IND", "BOMAT", "KBRUE", "KSPAE", "BOSTA", "KNUMA_PI", "KNUMA_AG", "KNUMA_SQ",
"VALTG", "VALDT", "ZTERM", "ANZAUF", "MIKBAS", "MXKBAS", "KOMXWRT", "KLF_STG", "KLF_KAL", "VKKAL",
"AKTNR", "KNUMA_BO", "MWSK2", "VERTT", "VERTN", "VBEWA", "MDFLG", "KFRST", "UASTA", "/BEV1/ECRTT",
"/BEV1/ECRTN", "/BEV1/ECEWA", "RN" FROM raw_ext."KONP_READ";