INSERT INTO stg."/RUSAL/DTL_PDX_H" ("MANDT", "EBELN", "NAME", "OE", "URL", "DOCID", "DOCIDINT", "PDX_LOAD", "STATUS", "PAYDOX_STATUS", "BEDAT",
"BSART_PD", "RN") 
SELECT "MANDT", "EBELN", "NAME", "OE", "URL", "DOCID", "DOCIDINT", "PDX_LOAD", "STATUS", "PAYDOX_STATUS", "BEDAT",
"BSART_PD", "RN" FROM raw_ext."/RUSAL/DTL_PDX_H_READ";