insert into ods."/rusal/ledisloc_ral"(
	"id",
	"pos",
	"type_load",
	"numvag",
	"numnakl",
	"traty",
	"daten",
	"knote_naz",
	"et_tarif",
	"knote1",
	"opcode",
	"datd",
	"uzeit",
	"knote2",
	"strekl2",
	"trno",
	"deliv_date",
	"distance_left",
	"erdat",
	"erzet",
	"ernam",
	"aedat",
	"aezet",
	"aenam",
	"date_sh"
)
select
	"ID" as "id",
	"POS" as "pos",
	"TYPE_LOAD" as "type_load",
	"NUMVAG" as "numvag",
	tech_etl.util_text_to_null_validation("NUMNAKL") as "numnakl",
	tech_etl.util_text_to_null_validation("TRATY") as "traty",
	tech_etl.util_text_to_date_validation("DATEN") as "daten",
	tech_etl.util_text_to_null_validation("KNOTE_NAZ") as "knote_naz",
	tech_etl.util_text_to_null_validation("ET_TARIF") as "et_tarif",
	tech_etl.util_text_to_null_validation("KNOTE1") as "knote1",
	tech_etl.util_text_to_null_validation("OPCODE") as "opcode",
	tech_etl.util_text_to_date_validation("DATD") as "datd",
	tech_etl.util_text_to_time_validation("UZEIT") as "uzeit",	
	tech_etl.util_text_to_null_validation("KNOTE2") as "knote2",
	tech_etl.util_text_to_null_validation("STREKL2") as "strekl2",
	tech_etl.util_text_to_null_validation("TRNO") as "trno",
	tech_etl.util_text_to_date_validation("DELIV_DATE") as "deliv_date",
	"DISTANCE_LEFT" as "distance_left",
	tech_etl.util_text_to_date_validation("ERDAT") as "erdat",
	tech_etl.util_text_to_time_validation("ERZET") as "erzet",
	tech_etl.util_text_to_null_validation("ERNAM") as "ernam",
	tech_etl.util_text_to_date_validation("AEDAT") as "aedat",
	tech_etl.util_text_to_time_validation("AEZET") as "aezet",
	tech_etl.util_text_to_null_validation("AENAM") as "aenam",
	tech_etl.util_text_to_date_validation("DATE_SH") as "date_sh"
from stg."/RUSAL/LEDISLOC"
where "MANDT" = '400';