INSERT INTO STG."/RUSAL/ZLE1424M" ("MANDT", "VBELN", "PR_CONT_FAKT", "PR_PL_FAKT", "EBELN_POD", "EBELP_POD", "EBELN_ZD", "EBELP_ZD", "EBELN_PR", "EBELP_PR", "CDATE", "CTIME", "USNAM", "SCHEME", "RN")
SELECT "MANDT", "VBELN", "PR_CONT_FAKT", "PR_PL_FAKT", "EBELN_POD", "EBELP_POD", "EBELN_ZD", "EBELP_ZD", "EBELN_PR", "EBELP_PR", "CDATE", "CTIME", "USNAM", "SCHEME", "RN"
FROM raw_ext."/RUSAL/ZLE1424M_READ";
