from __future__ import annotations


V5_REQUIRED_COLUMNS = [
    "fixture_id",
    "league_id",
    "season",
    "round",
    "match_start_utc",
    "prediction_time_utc",
    "mode",
    "hours_before_match",
    "home_team_id",
    "away_team_id",
    "home_goals",
    "away_goals",
    "target_result",
    "target_over25",
    "odds_snapshot_time_utc",
    "avg_odds_home_open",
    "avg_odds_draw_open",
    "avg_odds_away_open",
    "avg_odds_home_current",
    "avg_odds_draw_current",
    "avg_odds_away_current",
    "n_bookmakers_open",
    "n_bookmakers_current",
]


V5_OPTIONAL_PHASE1_COLUMNS = [
    "p_home_open",
    "p_draw_open",
    "p_away_open",
    "p_home_current",
    "p_draw_current",
    "p_away_current",
    "overround_open",
    "overround_current",
    "market_entropy_open",
    "market_entropy_current",
    "line_move_home",
    "line_move_draw",
    "line_move_away",
    "home_xg_for_5",
    "home_xga_5",
    "home_npxg_for_5",
    "home_npxga_5",
    "away_xg_for_5",
    "away_xga_5",
    "away_npxg_for_5",
    "away_npxga_5",
    "home_xg_for_home_5",
    "home_xga_home_5",
    "away_xg_for_away_5",
    "away_xga_away_5",
    "home_table_position",
    "away_table_position",
    "home_points_before",
    "away_points_before",
    "season_progress",
    "round_number",
    "home_must_win_score",
    "away_must_win_score",
    "late_season_flag",
]
