insert into stg."/RUSAL/EKKONT"
("MANDT", "EBELN", "WERKS", "EBELN_VENDER", "LIFNR", "VERKF", "UNSEZ", "VERKF40", "UNSEZ40", "DOPSG40", "HIDE", "EBELN_AGENT", "ELIFN_AGENT", "EVERK_AGENT", "UNSEZ_AGENT", "POS_X", "EBELN_CUSTOM", "RN")
SELECT "MANDT", "EBELN", "WERKS", "EBELN_VENDER", "LIFNR", "VERKF", "UNSEZ", "VERKF40", "UNSEZ40", "DOPSG40", "HIDE", "EBELN_AGENT", "ELIFN_AGENT", "EVERK_AGENT", "UNSEZ_AGENT", "POS_X", "EBELN_CUSTOM", "RN"
FROM raw_ext."/RUSAL/EKKONT_READ";