import argparse
import csv
import os
import subprocess
from pathlib import Path
from typing import List


DEFAULT_PSQL = "/Applications/Postgres.app/Contents/Versions/18/bin/psql"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Apply manual overrides to player_cross_source_map.")
    p.add_argument("--csv", required=True, help="CSV generated by generate_manual_overrides.py")
    p.add_argument("--db-host", default=os.getenv("PGHOST", "localhost"))
    p.add_argument("--db-port", default=os.getenv("PGPORT", "5432"))
    p.add_argument("--db-name", default=os.getenv("PGDATABASE", "dwh"))
    p.add_argument("--db-user", default=os.getenv("PGUSER", "postgres"))
    p.add_argument("--db-password", default=os.getenv("PGPASSWORD", "0506"))
    p.add_argument("--psql", default=DEFAULT_PSQL)
    return p.parse_args()


def run_sql(args: argparse.Namespace, sql: str) -> None:
    env = os.environ.copy()
    env["PGPASSWORD"] = args.db_password
    cmd = [
        args.psql,
        "-h",
        str(args.db_host),
        "-p",
        str(args.db_port),
        "-U",
        str(args.db_user),
        "-d",
        str(args.db_name),
        "-v",
        "ON_ERROR_STOP=1",
    ]
    proc = subprocess.run(cmd, input=sql, text=True, capture_output=True, env=env, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"psql failed:\n{proc.stderr}")


def q(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    args = parse_args()
    path = Path(args.csv)
    if not path.exists():
        raise RuntimeError(f"CSV not found: {path}")

    rows: List[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if str(r.get("apply", "0")).strip() not in {"1", "true", "True", "yes", "YES"}:
                continue
            if not r.get("understat_row_id") or not r.get("api_row_id"):
                continue
            rows.append(r)

    if not rows:
        print("[INFO] no rows with apply=1")
        return

    sqls = ["BEGIN;"]
    for r in rows:
        under_id = int(r["understat_row_id"])
        api_id = int(r["api_row_id"])
        reason = q(r.get("reason") or "manual_override")
        score = r.get("score") or "0.90"

        sqls.append(
            f"""
UPDATE football.player_cross_source_map u
SET api_player_id = a.api_player_id,
    api_player_name = a.api_player_name,
    api_team_id = a.api_team_id,
    api_team_name = a.api_team_name,
    mapping_method = 'manual_override_{reason}',
    confidence = {score},
    notes = 'from_csv',
    updated_dttm = NOW()
FROM football.player_cross_source_map a
WHERE u.id = {under_id}
  AND a.id = {api_id};
"""
        )
        sqls.append(f"DELETE FROM football.player_cross_source_map WHERE id = {api_id};")
    sqls.append("COMMIT;")
    run_sql(args, "\n".join(sqls))
    print(f"[OK] applied overrides: {len(rows)}")


if __name__ == "__main__":
    main()
