insert into stg."AUAK"
("MANDT", "BELNR", "KOKRS", "BUDAT", "BZDAT", "CPUDT", "WSDAT", "KURST", "GJAHR", "PERIO", "PERBZ", 
"OBJNR", "STFLG", "STBEL", "STOKZ", "ABSCH", "URSCH", "GMENG", "GEINH", "ANALG", "ABRNR", "KSTAR", 
"ERSCH", "SAPRL", "AWSYS", "CO_VAART", "BUPERIO", "BUGJAHR", "TIMESTMP", "PERIO_F", "PERIO_T", 
"VERSN", "WRTTP", "BLDAT", "RN")
SELECT "MANDT", "BELNR", "KOKRS", "BUDAT", "BZDAT", "CPUDT", "WSDAT", "KURST", "GJAHR", "PERIO", "PERBZ", 
"OBJNR", "STFLG", "STBEL", "STOKZ", "ABSCH", "URSCH", "GMENG", "GEINH", "ANALG", "ABRNR", "KSTAR", 
"ERSCH", "SAPRL", "AWSYS", "CO_VAART", "BUPERIO", "BUGJAHR", "TIMESTMP", "PERIO_F", "PERIO_T", "VERSN",
 "WRTTP", "BLDAT", "RN"
FROM raw_ext."AUAK_READ";