INSERT INTO stg."/RUSAL/PERF"
("MANDT", "WERKS", "ID", "POS", "BUKRS", "BELNR", "GJAHR", "BUDAT", "STBLG", "STJAH", "BUDAT_ST", "CPUDT", "USNAM", "TYPE", "STATE", "KOR_PREV", "KOR", "VBELN", "POSNR", "VBELN_KR", "CPUTM", "NOM_SC_KOR", "DATE_KOR", "RN")
SELECT "MANDT", "WERKS", "ID", "POS", "BUKRS", "BELNR", "GJAHR", "BUDAT", "STBLG", "STJAH", "BUDAT_ST", "CPUDT", "USNAM", "TYPE", "STATE", "KOR_PREV", "KOR", "VBELN", "POSNR", "VBELN_KR", "CPUTM", "NOM_SC_KOR", "DATE_KOR", "RN"
FROM raw_ext."/RUSAL/PERF_READ";